// Autogenerated code for vkmmc project
// Source file
#include "Framebuffer.h"
#include "Debug.h"

namespace vkmmc
{    
    FramebufferBuilder FramebufferBuilder::Create()
    {
        FramebufferBuilder builder;   
        return builder;
    }

    FramebufferBuilder& vkmmc::FramebufferBuilder::AddAttachment(VkImageView imageView)
    {
        m_attachments.push_back(imageView);
        return *this;
    }

	VkFramebuffer vkmmc::FramebufferBuilder::Build(VkDevice device, VkRenderPass renderPass, uint32_t width, uint32_t height)
    {
        VkFramebufferCreateInfo info
        {
            .sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO,
            .pNext = nullptr,
            .renderPass = renderPass,
            .attachmentCount = (uint32_t)m_attachments.size(),
            .pAttachments = m_attachments.data(),
            .width = width,
            .height = height,
            .layers = 1
        };
        VkFramebuffer framebuffer;
        vkcheck(vkCreateFramebuffer(device, &info, nullptr, &framebuffer));
        return framebuffer;
}

}
