// Autogenerated code for vkmmc project
// Header file

#pragma once

#include <vulkan/vulkan.h>
#include <vector>

namespace vkmmc
{
	struct RenderContext;

	struct FramebufferBuilder
	{
		static FramebufferBuilder Create();

		FramebufferBuilder& AddAttachment(VkImageView imageView);

		VkFramebuffer Build(VkDevice device,
			VkRenderPass renderPass,
			uint32_t width, 
			uint32_t height);
	private:
		FramebufferBuilder() = default;

		std::vector<VkImageView> m_attachments;
	};


}
