// Autogenerated code for vkmmc project
// Header file

#pragma once

namespace vkmmc
{
	namespace globals
	{
		// Assets reference
		extern const char* BasicVertexShader;
		extern const char* BasicFragmentShader;
		extern const char* LineVertexShader;
		extern const char* LineFragmentShader;

	}
}
