// Autogenerated code for vkmmc project
// Source file
#include <vulkan/vulkan_core.h>


#define ASSET_ROOT_PATH "../../assets/"
#define SHADER_ROOT_PATH ASSET_ROOT_PATH "shaders/"

namespace vkmmc
{
	namespace globals
	{
		// Assets reference
		const char* BasicVertexShader = SHADER_ROOT_PATH "basic.vert.spv";
		const char* BasicFragmentShader = SHADER_ROOT_PATH "basic.frag.spv";
		const char* LineVertexShader = SHADER_ROOT_PATH "line.vert.spv";
		const char* LineFragmentShader = SHADER_ROOT_PATH "line.frag.spv";

	}
}