// Autogenerated code for vkmmc project
// Header file

#pragma once

#define UNIFORM_ID_SCENE_MODEL_TRANSFORM_ARRAY "Models"
#define UNIFORM_ID_SCENE_ENV_DATA "Environment"
#define UNIFORM_ID_SHADOW_MAP_VP "ShadowMapVP"
#define UNIFORM_ID_CAMERA "Camera"


namespace vkmmc
{
	namespace globals
	{
		// Assets reference
		extern const char* BasicVertexShader;
		extern const char* BasicFragmentShader;
		extern const char* LineVertexShader;
		extern const char* LineFragmentShader;
		extern const char* DepthVertexShader;
		extern const char* DepthFragmentShader;
		extern const char* QuadVertexShader;
		extern const char* QuadFragmentShader;
		constexpr uint32_t MaxOverlappedFrames = 2;
		constexpr uint32_t MaxRenderObjects = 1000;
		constexpr uint32_t MaxShadowMapAttachments = 2;
	}
}
