// Autogenerated code for vkmmc project
// Source file
#include <vulkan/vulkan_core.h>


#define ASSET_ROOT_PATH "../../assets/"
#define SHADER_ROOT_PATH ASSET_ROOT_PATH "shaders/"

namespace vkmmc
{
	namespace globals
	{
		// Assets reference
		const char* BasicVertexShader = SHADER_ROOT_PATH "basic.vert.spv";
		const char* BasicFragmentShader = SHADER_ROOT_PATH "basic.frag.spv";
		const char* LineVertexShader = SHADER_ROOT_PATH "line.vert.spv";
		const char* LineFragmentShader = SHADER_ROOT_PATH "line.frag.spv";
		const char* DepthVertexShader = SHADER_ROOT_PATH "depth.vert.spv";
		const char* DepthFragmentShader = SHADER_ROOT_PATH "depth.frag.spv";
		const char* QuadVertexShader = SHADER_ROOT_PATH "quad.vert.spv";
		const char* QuadFragmentShader = SHADER_ROOT_PATH "quad.frag.spv";
		const char* DepthQuadFragmentShader = SHADER_ROOT_PATH "quad.frag.spv";
		const char* PostProcessVertexShader= SHADER_ROOT_PATH "quad.vert.spv";
		const char* PostProcessFragmentShader= SHADER_ROOT_PATH "postprocess_quad.frag.spv";

	}
}