// Autogenerated code for Mist project
// Header file

#pragma once
#include "Shader.h"
#include "Globals.h"
#include "VulkanBuffer.h"
#include <glm/glm.hpp>

namespace Mist
{
	class ComputeShader;

	struct Particle
	{
		glm::vec2 Position;
		glm::vec2 Velocity;
		glm::vec4 Color;
	};

	class GPUParticleSystem
	{
	public:

		void Init(const RenderContext& context);
		void Destroy(const RenderContext& context);

	private:
		ComputeShader* m_shader;
		AllocatedBuffer m_ssboArray[globals::MaxOverlappedFrames];
	};
}
