// Autogenerated code for Mist project
// Header file

#pragma once
#include <string.h>
#include "Core/Debug.h"
namespace Mist
{
	enum eResourceType
	{
		RESOURCE_NONE,
		RESOURCE_MESH,
		RESOURCE_MATERIAL,
		RESOURCE_TEXTURE
	};

	class cRenderResource
	{
	public:
		cRenderResource() : m_name{ 0 }, m_type(RESOURCE_NONE) {}
		const char* GetName() const { return m_name; }
		void SetName(const char* str) { check(*str); strcpy_s(m_name, str); }
		eResourceType GetType() const { return m_type; }
		void SetType(eResourceType type) { check(m_type == RESOURCE_NONE); m_type = type; }
	private:
		char m_name[64];
		eResourceType m_type;
	};
}
