// Autogenerated code for Mist project
// Header file

#pragma once
#include "Render/RenderContext.h"

namespace Mist
{
	class RenderTarget;

	namespace ui
	{
		void Init(const RenderContext& context, const RenderTarget& rt);
		void Destroy(const RenderContext& context);
		void Begin(const RenderContext& context);
		void End(const RenderContext& context);
	}
}
