// Autogenerated code for vkmmc project
// Header file

#pragma once
#include "RendererBase.h"

namespace vkmmc
{
	class DebugRenderer : public IRendererBase
	{
	public:
		virtual void Init(const RendererCreateInfo& info) override;
		virtual void Destroy(const RenderContext& renderContext) override;
		virtual void BeginFrame(const RenderContext& renderContext) override {}
		virtual void RecordCommandBuffer(const RenderContext& renderContext, RenderFrameContext& renderFrameContext) override;
	protected:
		// Render State
		VkDescriptorSet m_uniformSet;
		AllocatedBuffer m_uniformBuffer;
		RenderPipeline m_renderPipeline;
		VertexBuffer m_lineVertexBuffer;
	};
}
