// Autogenerated code for vkmmc project
// Source file
#include "ModelRenderer.h"
#include "Debug.h"
#include "InitVulkanTypes.h"
#include "Shader.h"
#include "Globals.h"
#include "VulkanRenderEngine.h"
#include "SceneImpl.h"
#include "imgui_internal.h"

#include "DebugRenderer.h"

namespace vkmmc
{
	ModelRenderer::ModelRenderer() : IRendererBase()
	{
		for (uint32_t i = 0; i < EnvironmentData::MaxLights; ++i)
			m_environmentData.Lights[i] = { .Position = {0.f, 0.f, 0.f}, .Radius = 10.f, .Color = {1.f, 1.f, 1.f}, .Compression = 0.5f, };
	}

	void ModelRenderer::Init(const RendererCreateInfo& info)
	{
		/**********************************/
		/** Pipeline layout and pipeline **/
		/**********************************/
		ShaderDescription shaderStageDescs[] =
		{
			{.Filepath = globals::BasicVertexShader, .Stage = VK_SHADER_STAGE_VERTEX_BIT},
			{.Filepath = globals::BasicFragmentShader, .Stage = VK_SHADER_STAGE_FRAGMENT_BIT}
		};
		m_renderPipeline = RenderPipeline::Create(
			info.RContext,
			info.RenderPass,
			0,
			shaderStageDescs,
			sizeof(shaderStageDescs) / sizeof(ShaderDescription),
			VertexInputLayout::GetStaticMeshVertexLayout()
		);

		m_frameData.resize(info.FrameUniformBufferArray.size());
		for (uint32_t i = 0; i < (uint32_t)info.FrameUniformBufferArray.size(); ++i)
		{
			UniformBuffer* uniformBuffer = info.FrameUniformBufferArray[i];
			uint32_t modelsSize = sizeof(glm::mat4) * VulkanRenderEngine::MaxRenderObjects;
			uint32_t modelsOffset = uniformBuffer->AllocUniform(info.RContext, "Models", modelsSize);
			VkDescriptorBufferInfo modelsDescInfo;
			modelsDescInfo.buffer = uniformBuffer->GetBuffer();
			modelsDescInfo.offset = modelsOffset;
			modelsDescInfo.range = modelsSize;
			uint32_t enviroSize = sizeof(EnvironmentData);
			uint32_t enviroOffset = uniformBuffer->AllocUniform(info.RContext, "Environment", enviroSize);
			VkDescriptorBufferInfo enviroDescInfo;
			enviroDescInfo.buffer = uniformBuffer->GetBuffer();
			enviroDescInfo.offset = enviroOffset;
			enviroDescInfo.range = enviroSize;

			DescriptorBuilder::Create(*info.LayoutCache, *info.DescriptorAllocator)
				.BindBuffer(0, modelsDescInfo, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, VK_SHADER_STAGE_VERTEX_BIT)
				.BindBuffer(1, enviroDescInfo, VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, VK_SHADER_STAGE_FRAGMENT_BIT)
				.Build(info.RContext, m_frameData[i].GlobalSet);
		}

		m_environmentData.AmbientColor = glm::vec4(0.01f, 0.01f, 0.01f, 1.f);
	}

	void ModelRenderer::Destroy(const RenderContext& renderContext)
	{
		m_renderPipeline.Destroy(renderContext);
	}

	void ModelRenderer::RecordCommandBuffer(const RenderContext& renderContext, RenderFrameContext& renderFrameContext)
	{
		// Update buffers
		// TODO: Get camera position from scene view.
		m_environmentData.ViewPosition = glm::inverse(renderFrameContext.CameraData->View)[3];
		renderFrameContext.GlobalBuffer.SetUniform(renderContext, "Models", renderFrameContext.Scene->GetRawGlobalTransforms(), sizeof(glm::mat4) * renderFrameContext.Scene->Count());
		renderFrameContext.GlobalBuffer.SetUniform(renderContext, "Environment", &m_environmentData, sizeof(EnvironmentData));

		// Bind pipeline
		VkCommandBuffer cmd = renderFrameContext.GraphicsCommand;
		vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, m_renderPipeline.GetPipelineHandle());

		// Bind global descriptor sets
		VkDescriptorSet sets[] = { renderFrameContext.CameraDescriptorSet, m_frameData[renderFrameContext.FrameIndex].GlobalSet };
		uint32_t setCount = sizeof(sets) / sizeof(VkDescriptorSet);
		vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, m_renderPipeline.GetPipelineLayoutHandle(), 0, setCount, sets, 0, nullptr);

		// Push constants if needed
		if (renderFrameContext.PushConstantData)
		{
			check(renderFrameContext.PushConstantSize);
			vkCmdPushConstants(cmd, m_renderPipeline.GetPipelineLayoutHandle(),
				VK_SHADER_STAGE_FRAGMENT_BIT, 0,
				renderFrameContext.PushConstantSize,
				renderFrameContext.PushConstantData);
		}

		// Iterate scene graph to render models.
		Material lastMaterial;
		Mesh lastMesh;
		Scene* scene = renderFrameContext.Scene;
		const Model* models = scene->GetModelArray();
		uint32_t modelCount = scene->GetModelCount();
		for (uint32_t i = 0; i < modelCount; ++i)
		{
			const Model& model = models[i];
			for (uint32_t meshIndex = 0; meshIndex < model.m_meshArray.size(); ++meshIndex)
			{
				Mesh mesh = model.m_meshArray[meshIndex];
				Material material = model.m_materialArray[meshIndex];
				if (mesh.GetHandle().IsValid() && material.GetHandle().IsValid())
				{
					if (material != lastMaterial || !lastMaterial.GetHandle().IsValid())
					{
						lastMaterial = material;
						RenderHandle mtlHandle = material.GetHandle();
						if (mtlHandle.IsValid())
						{
							const MaterialRenderData& texData = scene->GetMaterialRenderData(mtlHandle);;
							vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS,
								m_renderPipeline.GetPipelineLayoutHandle(), 2, 1, &texData.Set,
								0, nullptr);
						}
					}

					if (lastMesh != mesh)
					{
						check(mesh.GetHandle().IsValid());
						const MeshRenderData& meshRenderData = scene->GetMeshRenderData(mesh.GetHandle());
						meshRenderData.VertexBuffer.Bind(cmd);
						meshRenderData.IndexBuffer.Bind(cmd);
						lastMesh = mesh;
					}
					vkCmdDrawIndexed(cmd, (uint32_t)lastMesh.GetIndexCount(), 1, 0, 0, i);
				}
			}
		}
	}

	void ModelRenderer::ImGuiDraw()
	{
		ImGui::Begin("Environment");
		ImGui::ColorEdit3("Ambient color", &m_environmentData.AmbientColor[0]);
		ImGui::Text("ViewPos: %.3f, %.3f, %.3f", m_environmentData.ViewPosition.x, m_environmentData.ViewPosition.y, m_environmentData.ViewPosition.z);

		auto utilDragFloat = [](const char* label, uint32_t id, float* data, uint32_t count, float diff = 1.f, float minLimit = 0.f, float maxLimit = 0.f)
			{
				ImGui::Text(label);
				ImGui::SameLine();
				char buff[64];
				sprintf_s(buff, "##%s%u", label, id);
				switch (count)
				{
				case 1: return ImGui::DragFloat(buff, data, diff, minLimit, maxLimit); 
				case 2: return ImGui::DragFloat2(buff, data, diff, minLimit, maxLimit); 
				case 3: return ImGui::DragFloat3(buff, data, diff, minLimit, maxLimit); 
				case 4: return ImGui::DragFloat4(buff, data, diff, minLimit, maxLimit); 
				}
				return false;
			};

		for (uint32_t i = 0; i < EnvironmentData::MaxLights; ++i)
		{
			char buff[32];
			sprintf_s(buff, "Light_%u", i);
			if (ImGui::CollapsingHeader(buff))
			{
				utilDragFloat("Position", i, &m_environmentData.Lights[i].Position[0], 3);
				utilDragFloat("Color", i, &m_environmentData.Lights[i].Color[0], 3, 0.02f, 0.f, 1.f);
				utilDragFloat("Radius", i, &m_environmentData.Lights[i].Radius, 1, 0.5f, 0.f, FLT_MAX);
				utilDragFloat("Compression", i, &m_environmentData.Lights[i].Compression, 1, 0.5f, 0.5f, FLT_MAX);

				rdbg::DeferredDrawAxis(m_environmentData.Lights[i].Position, glm::vec3(0.f), glm::vec3(1.f));
				rdbg::DeferredDrawSphere(m_environmentData.Lights[i].Position, m_environmentData.Lights[i].Radius, m_environmentData.Lights[i].Color);
			}
		}
		ImGui::End();
	}
}
