// Autogenerated code for vkmmc project
// Header file

#pragma once
#include "RendererBase.h"

namespace vkmmc
{
	class ModelRenderer : public IRendererBase
	{
	public:
		virtual void Init(const RendererCreateInfo& info) override;
		virtual void Destroy(const RenderContext& renderContext) override;
		virtual void RecordCommandBuffer(const RenderFrameContext& renderFrameContext,
			const Model* models, uint32_t modelCount) override;
	private:
		void BeginRenderPass(const RenderFrameContext& renderFrameContext);
		void EndRenderPass(const RenderFrameContext& renderFrameContext);
	};
}
