// Autogenerated code for Mist project
// Source file
#include "Scene.h"
#include "Core/Logger.h"
#include "Core/Debug.h"

#define CGLTF_IMPLEMENTATION
#pragma warning(disable:4996)
#include <gltf/cgltf.h>
#undef CGLTF_IMPLEMENTATION

#ifdef MIST_MEM_MANAGEMENT
// TODO: wtf windows declare these macros and project does not compile when MIST_MEM_MANAGEMENT is defined. WTF!?
#undef min
#undef max  
#endif // MIST_MEM_MANAGEMENT

#include <glm/gtx/transform.hpp>
#include <glm/gtx/quaternion.hpp>
#include <glm/gtx/euler_angles.hpp>
#include <glm/fwd.hpp>
#include "Render/Mesh.h"
#include "Utils/GenericUtils.h"
#include "Render/VulkanRenderEngine.h"
#include <algorithm>
#include <imgui.h>

#define SCENE_LOAD_YAML
#ifdef SCENE_LOAD_YAML

#include <yaml-cpp/yaml.h>

#endif // SCENE_LOAD_YAML
#include <fstream>
#include "Core/SystemMemory.h"
#include "Utils/TimeUtils.h"

//#define MIST_ENABLE_LOADER_LOG

#ifdef SCENE_LOAD_YAML
YAML::Emitter& operator<<(YAML::Emitter& e, const glm::vec3& v)
{
	e << YAML::Flow << YAML::BeginSeq << v.x << v.y << v.z << YAML::EndSeq;
	return e;
}

YAML::Emitter& operator<<(YAML::Emitter& e, const glm::vec4& v)
{
	e << YAML::Flow << YAML::BeginSeq << v.x << v.y << v.z << v.w << YAML::EndSeq;
	return e;
}

namespace YAML
{
	template<>
	struct convert<glm::vec2>
	{
		static Node encode(const glm::vec2& rhs)
		{
			Node node;
			node.push_back(rhs.x);
			node.push_back(rhs.y);
			return node;
		}

		static bool decode(const Node& node, glm::vec2& rhs)
		{
			if (!node.IsSequence() || node.size() != 2)
				return false;

			rhs.x = node[0].as<float>();
			rhs.y = node[1].as<float>();
			return true;
		}
	};

	template<>
	struct convert<glm::vec3>
	{
		static Node encode(const glm::vec3& rhs)
		{
			Node node;
			node.push_back(rhs.x);
			node.push_back(rhs.y);
			node.push_back(rhs.z);
			return node;
		}

		static bool decode(const Node& node, glm::vec3& rhs)
		{
			if (!node.IsSequence() || node.size() != 3)
				return false;

			rhs.x = node[0].as<float>();
			rhs.y = node[1].as<float>();
			rhs.z = node[2].as<float>();
			return true;
		}
	};
}

#endif

#define GLTF_LOAD_GEOMETRY_POSITION 0x01
#define GLTF_LOAD_GEOMETRY_NORMAL 0x02
#define GLTF_LOAD_GEOMETRY_COLOR 0x04
#define GLTF_LOAD_GEOMETRY_TANGENT 0x08
#define GLTF_LOAD_GEOMETRY_TEXCOORDS 0x10
#define GLTF_LOAD_GEOMETRY_JOINTS 0x20
#define GLTF_LOAD_GEOMETRY_WEIGHTS 0x40
#define GLTF_LOAD_GEOMETRY_ALL 0xff

namespace gltf_api
{
	void HandleError(cgltf_result result, const char* filepath)
	{
		switch (result)
		{
		case cgltf_result_success:
			break;
		case cgltf_result_data_too_short:
			break;
		case cgltf_result_unknown_format:
			break;
		case cgltf_result_invalid_json:
			break;
		case cgltf_result_invalid_gltf:
			break;
		case cgltf_result_invalid_options:
			break;
		case cgltf_result_file_not_found:
			break;
		case cgltf_result_io_error:
			break;
		case cgltf_result_out_of_memory:
			break;
		case cgltf_result_legacy_gltf:
			break;
		case cgltf_result_max_enum:
			break;
		default:
			break;
		}
	}

	float Length2(const glm::vec3& vec)
	{
		return vec.x * vec.x + vec.y * vec.y + vec.z * vec.z;
	}

	float Length(const glm::vec3& vec) { return sqrtf(Length2(vec)); }

	uint32_t GetElementCountFromType(cgltf_type type)
	{
		switch (type)
		{
		case cgltf_type_scalar: return 1;
		case cgltf_type_vec2: return 2;
		case cgltf_type_vec3: return 3;
		case cgltf_type_vec4: return 4;
		case cgltf_type_mat2: return 2 * 2;
		case cgltf_type_mat3: return 3 * 3;
		case cgltf_type_mat4: return 4 * 4;
		case cgltf_type_invalid:
		case cgltf_type_max_enum:
		default:
			check(false && "Invalid cgltf_type.");
			break;
		}
		return 0;
	}

	void ReadValue(void* dst, const cgltf_float* data, uint32_t count)
	{
		memcpy_s(dst, sizeof(float) * count, data, sizeof(float) * count);
	}

	void ToMat4(glm::mat4* mat, const cgltf_float* cgltfMat4)
	{
		ReadValue(mat, cgltfMat4, 16);
	}

	void ToVec2(glm::vec2& v, const cgltf_float* data)
	{
		ReadValue(&v, data, 2);
	}

	void ToVec3(glm::vec3& v, const cgltf_float* data)
	{
		ReadValue(&v, data, 3);
	}

	void ToVec4(glm::vec4& v, const cgltf_float* data)
	{
		ReadValue(&v, data, 4);
	}

	void ToQuat(glm::quat& q, const cgltf_float* data)
	{
		q = glm::quat(data[3], data[0], data[1], data[2]);
	}

	void ReadNodeLocalTransform(const cgltf_node& node, glm::mat4& t)
	{
		t = glm::mat4(1.f);
		if (node.has_matrix)
		{
			gltf_api::ToMat4(&t, node.matrix);
		}
		else
		{
			if (node.has_translation)
			{
				glm::vec3 pos;
				gltf_api::ToVec3(pos, node.translation);
				t *= glm::translate(t, pos);
			}
			if (node.has_rotation)
			{
				glm::quat quat;
				gltf_api::ToQuat(quat, node.rotation);
				t *= glm::toMat4(quat);
			}
			if (node.has_scale)
			{
				glm::vec3 scl;
				gltf_api::ToVec3(scl, node.scale);
				t = glm::scale(t, scl);
			}
		}
	}

	void ReadValues(Mist::tDynArray<float>& values, const cgltf_accessor& accessor)
	{
		uint32_t elementCount = GetElementCountFromType(accessor.type);
		values.resize(accessor.count * elementCount);
		for (uint32_t i = 0; i < accessor.count; ++i)
			cgltf_accessor_read_float(&accessor, i, &values[i * elementCount], elementCount);
	}

	void ReadAttribute(Mist::Vertex& vertex, const float* source, uint32_t index, cgltf_attribute_type type)
	{
		const char* attributeName = nullptr;
		const float* data = &source[index];
		switch (type)
		{
		case cgltf_attribute_type_position:
			ToVec3(vertex.Position, data);
			break;
		case cgltf_attribute_type_texcoord:
			ToVec2(vertex.TexCoords, data);
			break;
		case cgltf_attribute_type_normal:
			ToVec3(vertex.Normal, data);
			if (Length2(vertex.Normal) < 1e-5f)
				vertex.Normal = glm::vec3{ 0.f, 1.f, 0.f };
			else
				vertex.Normal = glm::normalize(vertex.Normal);
			break;
		case cgltf_attribute_type_color:
			ToVec3(vertex.Color, data);
			break;
		case cgltf_attribute_type_tangent:
			ToVec3(vertex.Tangent, data);
			break;
		case cgltf_attribute_type_joints:
#ifdef MIST_ENABLE_LOADER_LOG
			attributeName = "joints";
#endif // MIST_ENABLE_LOADER_LOG

			break;
		case cgltf_attribute_type_weights:
#ifdef MIST_ENABLE_LOADER_LOG
			attributeName = "weights";
#endif // MIST_ENABLE_LOADER_LOG
			break;
		case cgltf_attribute_type_invalid:
		case cgltf_attribute_type_custom:
		case cgltf_attribute_type_max_enum:
			check(false && "Invalid attribute type to read.");
		default:
			break;
		}
#ifdef MIST_ENABLE_LOADER_LOG
		if (attributeName)
			Mist::Logf(Mist::LogLevel::Error, "gltf loader: Attribute type not suported yet [%s].\n", attributeName);
#endif // MIST_ENABLE_LOADER_LOG

	}

	// Attributes are an continuous array of positions, normals, uvs...
	// We have to map from struct of arrays to our format, array of structs (tDynArray<Mist::Vertex>)
	void ReadAttributeArray(Mist::Vertex* vertices, const cgltf_attribute& attribute)
	{
		const cgltf_accessor* accessor = attribute.data;
		uint32_t accessorCount = (uint32_t)accessor->count;
		// Get how many values has current attribute
		uint32_t elementCount = GetElementCountFromType(accessor->type);
		// Read data from accessor
		Mist::tDynArray<float> values;
		ReadValues(values, *accessor);
		// Map to internal format
		for (uint32_t i = 0; i < accessorCount; ++i)
		{
			Mist::Vertex& vertex = vertices[i];
			uint32_t indexValue = i * elementCount;
			ReadAttribute(vertex, values.data(), indexValue, attribute.type);
		}
	}

	void FreeData(cgltf_data* data)
	{
		cgltf_free(data);
	}

	cgltf_data* ParseFile(const char* filepath)
	{
		cgltf_options options;
		memset(&options, 0, sizeof(cgltf_options));
		cgltf_data* data{ nullptr };
		cgltf_result result = cgltf_parse_file(&options, filepath, &data);
		if (result != cgltf_result_success)
		{
			HandleError(result, filepath);
			return nullptr;
		}
		result = cgltf_load_buffers(&options, data, filepath);
		if (result != cgltf_result_success)
		{
			HandleError(result, filepath);
			return nullptr;
		}
		result = cgltf_validate(data);
		if (result != cgltf_result_success)
		{
			HandleError(result, filepath);
			FreeData(data);
			return nullptr;
		}
		return data;
	}

	void LoadVertices(Mist::tDynArray<Mist::Vertex>& vertices, const cgltf_primitive* primitive, const cgltf_node* nodes, uint32_t nodeCount)
	{
		uint32_t attributeCount = (uint32_t)primitive->attributes_count;
		uint32_t vertexOffset = (uint32_t)vertices.size();
		uint32_t vertexCount = (uint32_t)primitive->attributes[0].data->count;
		vertices.resize(vertexCount + vertexOffset);
		for (uint32_t i = 0; i < attributeCount; ++i)
		{
			const cgltf_attribute& attribute = primitive->attributes[i];
			check(attribute.data->count == vertexCount);
			ReadAttributeArray(vertices.data() + vertexOffset, attribute);
		}
	}

	void LoadVertices(const cgltf_primitive& primitive, Mist::Vertex* verticesOut, uint32_t vertexCount)
	{
		uint32_t attributeCount = (uint32_t)primitive.attributes_count;
		for (uint32_t i = 0; i < attributeCount; ++i)
		{
			const cgltf_attribute& attribute = primitive.attributes[i];
			check(attribute.data->count <= vertexCount);
			ReadAttributeArray(verticesOut, attribute);
		}
	}

	void LoadIndices(Mist::tDynArray<uint32_t>& indices, const cgltf_primitive* primitive, uint32_t offset)
	{
		check(primitive->indices);
		uint32_t indexCount = (uint32_t)primitive->indices->count;
		uint32_t indexOffset = (uint32_t)indices.size();
		indices.resize(indexCount + indexOffset);
		for (uint32_t i = 0; i < indexCount; ++i)
			indices[i + indexOffset] = (uint32_t)cgltf_accessor_read_index(primitive->indices, i) + offset;
	}

	void LoadIndices(const cgltf_primitive& primitive, uint32_t* indicesOut, uint32_t offset)
	{
		check(primitive.indices && primitive.type == cgltf_primitive_type_triangles);
		uint32_t indexCount = (uint32_t)primitive.indices->count;
		for (uint32_t i = 0; i < indexCount; ++i)
			indicesOut[i] = (uint32_t)cgltf_accessor_read_index(primitive.indices, i) + offset;
	}

	bool LoadTexture(const Mist::RenderContext& context, const char* rootAssetPath, const cgltf_texture_view& texView, Mist::EFormat format, Mist::Texture** texOut)
	{
		if (!texView.texture)
			return false;
		char texturePath[512];
		sprintf_s(texturePath, "%s%s", rootAssetPath, texView.texture->image->uri);
		check(Mist::LoadTextureFromFile(context, texturePath, texOut, format));
		return true;
	}

#if 0
	void LoadMaterial(const Mist::RenderContext& context, Mist::Scene& scene, const char* rootAssetPath, Mist::cMaterial& material, const cgltf_material& mtl)
	{
		check(mtl.name);
		material.SetName(mtl.name);
		if (mtl.pbr_metallic_roughness.base_color_texture.texture)
		{
			Mist::Texture* diffuse;
			check(LoadTexture(context,
				rootAssetPath,
				mtl.pbr_metallic_roughness.base_color_texture, Mist::FORMAT_R8G8B8A8_SRGB, &diffuse));
			Mist::RenderHandle h = scene.SubmitTexture(diffuse);
			material.SetAlbedoTexture(h);
		}
		else
		{
#ifdef MIST_ENABLE_LOADER_LOG
			Mist::Log(Mist::LogLevel::Warn, "Diffuse material texture not found.\n");
#endif // MIST_ENABLE_LOADER_LOG
	}
		if (mtl.pbr_metallic_roughness.metallic_roughness_texture.texture)
		{
			Mist::Texture* diffuse;
			check(LoadTexture(context,
				rootAssetPath,
				mtl.pbr_metallic_roughness.metallic_roughness_texture, Mist::FORMAT_R8G8B8A8_SRGB, &diffuse));
			Mist::RenderHandle h = scene.SubmitTexture(diffuse);
			material.SetMetallicTexture(h);
		}
		else
		{
#ifdef MIST_ENABLE_LOADER_LOG
			Mist::Log(Mist::LogLevel::Warn, "Diffuse material texture not found.\n");
#endif // MIST_ENABLE_LOADER_LOG
		}
		material.SetMetallic(mtl.pbr_metallic_roughness.metallic_factor);
		material.SetRoughness(mtl.pbr_metallic_roughness.roughness_factor);

		if (mtl.pbr_specular_glossiness.diffuse_texture.texture)
		{
			Mist::Texture* tex;
			check(LoadTexture(context,
				rootAssetPath,
				mtl.pbr_specular_glossiness.diffuse_texture, Mist::FORMAT_R8G8B8A8_UNORM, &tex));
			Mist::RenderHandle h = scene.SubmitTexture(tex);
			material.SetSpecularTexture(h);
		}
#ifdef MIST_ENABLE_LOADER_LOG
		else
			Mist::Log(Mist::LogLevel::Warn, "Specular material texture not found.\n");
#endif // MIST_ENABLE_LOADER_LOG

		if (mtl.normal_texture.texture)
		{
			Mist::Texture* tex;
			check(LoadTexture(context,
				rootAssetPath,
				mtl.normal_texture, Mist::FORMAT_R8G8B8A8_UNORM, &tex));
			Mist::RenderHandle h = scene.SubmitTexture(tex);
			material.SetNormalTexture(h);
		}
#ifdef MIST_ENABLE_LOADER_LOG
		else
			Mist::Log(Mist::LogLevel::Warn, "Normal material texture not found.\n");
#endif // MIST_ENABLE_LOADER_LOG

		if (mtl.occlusion_texture.texture)
		{
			Mist::Texture* tex;
			check(LoadTexture(context, rootAssetPath, mtl.occlusion_texture, Mist::FORMAT_R8G8B8A8_UNORM, &tex));
			Mist::RenderHandle h = scene.SubmitTexture(tex);
			material.SetOcclusionTexture(h);
		}
#ifdef MIST_ENABLE_LOADER_LOG
		else
			Mist::Log(Mist::LogLevel::Warn, "Occlusion material texture not found.\n");
#endif // MIST_ENABLE_LOADER_LOG
		}
#endif // 0


	template <typename T>
	inline uint32_t GetArrayElementOffset(const T* root, const T* item) { check(item >= root); return item - root; }

#if 0
	void LoadGeometry(Mist::cMesh& mesh, Mist::tDynArray<Mist::PrimitiveMeshData>& primitives, const std::unordered_map<cgltf_material*, uint32_t>& materialMap, const cgltf_node& node, const cgltf_data& scene)
	{
		check(node.mesh && node.mesh->name);
		mesh.SetName(node.mesh->name);

		Mist::tDynArray<Mist::Vertex> vertices;
		Mist::tDynArray<uint32_t> indices;
		primitives.resize(node.mesh->primitives_count);

		for (uint32_t j = 0; j < node.mesh->primitives_count; ++j)
		{
			const cgltf_primitive& primitive = node.mesh->primitives[j];
			uint32_t vertexOffset = (uint32_t)vertices.size();
			primitives[j].FirstIndex = (uint32_t)indices.size();
			gltf_api::LoadIndices(indices, &primitive, vertexOffset);
			gltf_api::LoadVertices(vertices, &primitive, scene.nodes, (uint32_t)scene.nodes_count);
			primitives[j].Count = (uint32_t)indices.size() - primitives[j].FirstIndex;
			check(materialMap.contains(primitive.material));
			primitives[j].MaterialIndex = materialMap.at(primitive.material);
			check(primitive.indices->count == primitives[j].Count);
		}

		// Sort primitives by index
		std::sort(primitives.begin(), primitives.end(),
			[](const Mist::PrimitiveMeshData& a, const Mist::PrimitiveMeshData& b) {return a.MaterialIndex < b.MaterialIndex; }
		);

		mesh.MoveIndicesFrom(indices);
		mesh.MoveVerticesFrom(vertices);
	}
#endif // 0


	void LoadMaterial(Mist::cMaterial& material, const Mist::RenderContext& context, const cgltf_material& cgltfmtl, const char* rootAssetPath)
	{
		const cgltf_texture_view* views[Mist::MATERIAL_TEXTURE_COUNT] = {
			&cgltfmtl.pbr_metallic_roughness.base_color_texture,
			&cgltfmtl.normal_texture,
			&cgltfmtl.pbr_specular_glossiness.specular_glossiness_texture,
			&cgltfmtl.occlusion_texture,
			&cgltfmtl.pbr_metallic_roughness.metallic_roughness_texture,
			&cgltfmtl.emissive_texture
		};
		Mist::EFormat format = Mist::FORMAT_R8G8B8A8_SRGB;
		for (uint32_t i = 0; i < Mist::MATERIAL_TEXTURE_COUNT; ++i)
		{
			if (!LoadTexture(context, rootAssetPath, *views[i],
				format, &material.m_textures[i]))
				Mist::Logf(Mist::LogLevel::Error, "Material texture not found [%d][%s|%s]\n", i, rootAssetPath, cgltfmtl.name);
			else
				material.m_textures[i]->CreateView(context, Mist::tViewDescription());
		}
	}

}

namespace Mist
{
	const char* LightTypeToStr(ELightType e)
	{
		switch (e)
		{
		case ELightType::Point: return "Point";
		case ELightType::Directional: return "Directional";
		case ELightType::Spot: return "Spot";
		}
		check(false);
		return nullptr;
	}

	ELightType StrToLightType(const char* str)
	{
		if (!strcmp(str, "Point")) return ELightType::Point;
		if (!strcmp(str, "Spot")) return ELightType::Spot;
		if (!strcmp(str, "Directional")) return ELightType::Directional;
		check(false);
		return (ELightType)0xff;
	}

	void TransformComponentToMatrix(const TransformComponent* transforms, glm::mat4* matrices, uint32_t count)
	{
		for (uint32_t i = 0; i < count; ++i)
			matrices[i] = math::ToMat4(transforms[i].Position, transforms[i].Rotation, transforms[i].Scale);
	}

	template <uint32_t N>
	void GetResourceFileId(const char* file, const char* resname, char(&buff)[N])
	{
		sprintf_s(buff, "%s|%s", file, resname);
	}

	EnvironmentData::EnvironmentData() :
		AmbientColor(0.02f, 0.02f, 0.02f),
		ActiveSpotLightsCount(0.f),
		ViewPosition(0.f),
		ActiveLightsCount(0.f)
	{
		DirectionalLight.Color = { 0.01f, 0.01f, 0.1f };
		DirectionalLight.Position = { 0.f, 0.f, 1.f };
		DirectionalLight.ShadowMapIndex = -1.f;
		DirectionalLight.Compression = 0.5f;
		for (uint32_t i = 0; i < MaxLights; ++i)
		{
			Lights[i] = DirectionalLight;
			Lights[i].Radius = 50.f;
			SpotLights[i].Direction = { 1.f, 0.f, 0.f };
			SpotLights[i].Position = { 0.f, 0.f, 0.f };
			SpotLights[i].Color = { 1.f, 1.f, 1.f };
			SpotLights[i].InnerCutoff = 1.f;
			SpotLights[i].OuterCutoff = 0.5f;
			SpotLights[i].ShadowMapIndex = -1.f;
		}
		ZeroMem(this, sizeof(*this));
		AmbientColor = { 0.02f, 0.02f, 0.02f };
	}

	Scene::Scene(IRenderEngine* engine) : m_engine(static_cast<VulkanRenderEngine*>(engine))
	{
		// Create root scene
		//CreateRenderObject(RenderObject::InvalidId);
	}

	Scene::~Scene()
	{}

	void Scene::Init()
	{
		// default material
		CreateMaterial("default");
	}

	void Scene::Destroy()
	{
#if 0

		if (m_engine->GetScene() == this)
			m_engine->SetScene(nullptr);
#endif // 0

		const RenderContext& renderContext = m_engine->GetContext();

		for (uint32_t i = 0; i < m_meshes.size(); ++i)
			m_meshes[i].Destroy(renderContext);
		for (uint32_t i = 0; i < (uint32_t)m_materialArray.size(); ++i)
			m_materialArray[i].Destroy(m_engine->GetContext());
		for (uint32_t i = 0; i < (uint32_t)m_textures.size(); ++i)
			Texture::Destroy(m_engine->GetContext(), m_textures[i]);

		m_meshes.clear();
		m_materialArray.clear();
		m_textures.clear();
		m_localTransforms.clear();
		m_globalTransforms.clear();
		m_hierarchy.clear();
		m_names.clear();
		for (uint32_t i = 0; i < MaxNodeLevel; ++i)
			m_dirtyNodes[i].clear();
	}

	void Scene::InitFrameData(const RenderContext& renderContext, RenderFrameContext& frameContext)
	{
#if 0
		frameContext.GlobalBuffer.AllocDynamicUniform(renderContext, "Material", sizeof(MaterialUniform), MIST_MAX_MATERIALS);
		VkDescriptorBufferInfo info = frameContext.GlobalBuffer.GenerateDescriptorBufferInfo("Material");
		DescriptorBuilder::Create(*renderContext.LayoutCache, *renderContext.DescAllocator)
			.BindBuffer(0, &info, 1, VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC, VK_SHADER_STAGE_FRAGMENT_BIT)
			.Build(renderContext, m_materialSetArray[frameContext.FrameIndex]);
#endif // 0

	}

	sRenderObject Scene::CreateRenderObject(sRenderObject parent)
	{
		// Generate new node in all basics structures
		sRenderObject node = (uint32_t)m_hierarchy.size();
		m_localTransforms.push_back(glm::mat4(1.f));
		m_globalTransforms.push_back(glm::mat4(1.f));
		m_transformComponents.push_back({ .Position = glm::vec3(0.f), .Rotation = glm::vec3(0.f), .Scale = glm::vec3(1.f) });
		char buff[64];
		sprintf_s(buff, "RenderObject_%u", node.Id);
		m_names.push_back(buff);
		m_hierarchy.push_back({ .Parent = parent });

		// Connect siblings
		if (parent.IsValid())
		{
			check(parent.Id < (uint32_t)m_hierarchy.size());
			sRenderObject firstSibling = m_hierarchy[parent].Child;
			if (firstSibling.IsValid())
			{
				sRenderObject sibling;
				for (sibling = firstSibling; m_hierarchy[sibling].Sibling.IsValid(); sibling = m_hierarchy[sibling].Sibling);
				m_hierarchy[sibling].Sibling = node;
			}
			else
			{
				m_hierarchy[parent].Child = node;
			}
		}

		m_hierarchy[node].Level = parent.IsValid() ? m_hierarchy[parent].Level + 1 : 0;
		m_hierarchy[node].Child = InvalidIndex;
		m_hierarchy[node].Sibling = InvalidIndex;
		return node;
	}

	bool Scene::LoadModel(const RenderContext& context, const char* filepath)
	{
		check(false);
		cgltf_data* data = gltf_api::ParseFile(filepath);
		char rootAssetPath[512];
		io::GetDirectoryFromFilepath(filepath, rootAssetPath, 512);
		if (!data)
		{
			Logf(LogLevel::Error, "Cannot open file to load scene model: %s.\n", filepath);
			return false;
		}

		for (uint32_t i = 0; i < data->materials_count; ++i)
		{
			cMaterial* m = CreateMaterial(data->materials[i].name);
			gltf_api::LoadMaterial(*m, context, data->materials[i], rootAssetPath);
		}

		uint32_t nodesCount = (uint32_t)data->nodes_count;
		uint32_t renderObjectOffset = GetRenderObjectCount();

		tDynArray<Vertex> tempVertices;
		tDynArray<uint32_t> tempIndices;
		for (uint32_t i = 0; i < nodesCount; ++i)
		{
			const cgltf_node& node = data->nodes[i];
			sRenderObject parent = GetRoot();
			if (node.parent)
			{
				for (uint32_t j = 0; j < i; ++j)
				{
					if (&data->nodes[j] == node.parent)
					{
						parent = j + renderObjectOffset;
						break;
					}
				}
			}
			sRenderObject renderObject = CreateRenderObject(parent);

			// Process transform
			glm::mat4 localTransform(1.f);
			gltf_api::ReadNodeLocalTransform(node, localTransform);
			TransformComponent t;
			math::DecomposeMatrix(localTransform, t.Position, t.Rotation, t.Scale);
			SetTransform(renderObject, t);

			// Process mesh
			if (node.mesh)
			{
				m_meshes.push_back(cMesh());
				cMesh& mesh = m_meshes.back();
				mesh.SetName(node.mesh->name);
				tDynArray<PrimitiveMeshData>& primitives = mesh.PrimitiveArray;
				primitives.resize(node.mesh->primitives_count);
				for (uint32_t j = 0; j < node.mesh->primitives_count; ++j)
				{
					const cgltf_primitive& cgltfprimitive = node.mesh->primitives[j];
					PrimitiveMeshData& primitive = primitives[j];
					check(cgltfprimitive.type == cgltf_primitive_type_triangles);
					check(cgltfprimitive.indices && cgltfprimitive.indices->type == cgltf_type_scalar && cgltfprimitive.indices->count % 3 == 0);
					check(cgltfprimitive.attributes && cgltfprimitive.attributes->data);

					uint32_t indexCount = cgltfprimitive.indices->count;
					uint32_t vertexCount = cgltfprimitive.attributes[0].data->count;
					uint32_t vertexOffset = (uint32_t)tempVertices.size();
					uint32_t indexOffset = (uint32_t)tempIndices.size();
					tempIndices.resize(indexOffset + indexCount);
					tempVertices.resize(vertexOffset + vertexCount);

					primitive.FirstIndex = indexOffset;
					primitive.Count = indexCount;

					gltf_api::LoadIndices(cgltfprimitive, tempIndices.data() + indexOffset, vertexOffset);
					gltf_api::LoadVertices(cgltfprimitive, tempVertices.data() + vertexOffset, vertexCount);

					cMaterial* material = GetMaterial(cgltfprimitive.material->name);
					check(material);
					primitive.Material = material;

					check(cgltfprimitive.indices->count == primitive.Count);
				}

				// Submit data
				// Create mesh component associated
				MeshComponent mc;
				strcpy_s(mc.MeshAssetPath, filepath);
				mc.MeshName = node.mesh->name;
				mc.MeshIndex = (uint32_t)m_meshes.size();

				SetMesh(renderObject, mc);

				if (node.mesh->name && *node.mesh->name)
					SetRenderObjectName(renderObject, node.mesh->name);
			}
		}
		gltf_api::FreeData(data);
		return true;
	}

	void Scene::LoadScene(const RenderContext& context, const char* filepath)
	{
		io::File file;
		check(file.Open(filepath, "r"));
		uint32_t size = file.GetContentSize();
		char* content = _new char[size];
		uint32_t contentReaded = file.Read(content, size, sizeof(char), size);
		file.Close();
		check(contentReaded <= size);
		content[contentReaded == size ? size - 1 : contentReaded] = 0;

		YAML::Node root = YAML::Load(content);
		check(root);
		YAML::Node envNode = root["Environment"];
		check(envNode);
		m_ambientColor = envNode["Ambient"].as<glm::vec3>();
		char skyboxTextures[Skybox::COUNT][256];
		strcpy_s(skyboxTextures[Skybox::FRONT], envNode["Skybox"]["Front"].as<std::string>().c_str());
		strcpy_s(skyboxTextures[Skybox::BACK], envNode["Skybox"]["Back"].as<std::string>().c_str());
		strcpy_s(skyboxTextures[Skybox::TOP], envNode["Skybox"]["Top"].as<std::string>().c_str());
		strcpy_s(skyboxTextures[Skybox::BOTTOM], envNode["Skybox"]["Bottom"].as<std::string>().c_str());
		strcpy_s(skyboxTextures[Skybox::LEFT], envNode["Skybox"]["Left"].as<std::string>().c_str());
		strcpy_s(skyboxTextures[Skybox::RIGHT], envNode["Skybox"]["Right"].as<std::string>().c_str());
		LoadSkybox(m_engine->GetContext(), m_skybox,
			skyboxTextures[Skybox::FRONT],
			skyboxTextures[Skybox::BACK],
			skyboxTextures[Skybox::LEFT],
			skyboxTextures[Skybox::RIGHT],
			skyboxTextures[Skybox::TOP],
			skyboxTextures[Skybox::BOTTOM]);



		YAML::Node renderObjectSeq = root["RenderObjects"];
		check(renderObjectSeq);
		for (const auto& it : renderObjectSeq)
		{
			uint32_t parent = it["Parent"].as<uint32_t>();
			sRenderObject rb = CreateRenderObject(parent);
			SetRenderObjectName(rb, it["Name"].as<std::string>().c_str());

			TransformComponent t;
			YAML::Node transformNode = it["TransformComponent"];
			t.Position = transformNode["Position"].as<glm::vec3>();
			t.Rotation = transformNode["Rotation"].as<glm::vec3>();
			t.Scale = transformNode["Scale"].as<glm::vec3>();
			SetTransform(rb, t);

			YAML::Node lightNode = it["LightComponent"];
			if (lightNode)
			{
				LightComponent lightComponent;
				lightComponent.Color = lightNode["Color"].as<glm::vec3>();
				lightComponent.Radius = lightNode["Radius"].as<float>();
				lightComponent.Compression = lightNode["Compression"].as<float>();
				lightComponent.InnerCutoff = lightNode["InnerCutoff"].as<float>();
				lightComponent.OuterCutoff = lightNode["OuterCutoff"].as<float>();
				lightComponent.ProjectShadows = lightNode["ProjectShadows"].as<bool>();
				lightComponent.Type = StrToLightType(lightNode["Type"].as<std::string>().c_str());
				SetLight(rb, lightComponent);
			}

			YAML::Node meshNode = it["MeshComponent"];
			if (meshNode)
			{
				MeshComponent m;
				strcpy_s(m.MeshAssetPath, meshNode["MeshAssetPath"].as<std::string>().c_str());
				m.MeshName = meshNode["MeshName"].as<std::string>();
				m.MeshIndex = UINT32_MAX;
				if (!m_meshNameIndexMap.contains(m.MeshAssetPath))
					check(LoadMeshesFromFile(context, m.MeshAssetPath));
				char buff[256];
				GetResourceFileId(m.MeshAssetPath, m.MeshName.c_str(), buff);
				check(m_meshNameIndexMap.contains(buff));
				m.MeshIndex = m_meshNameIndexMap[buff];
				SetMesh(rb, m);
			}
		}
		delete[] content;
	}

	void Scene::SaveScene(const RenderContext& context, const char* filepath)
	{
		YAML::Emitter emitter;

		emitter << YAML::BeginMap;
		emitter << YAML::Key << "Environment";
		{
			emitter << YAML::BeginMap;
			emitter << YAML::Key << "Ambient" << YAML::Value << m_ambientColor;
			emitter << YAML::Key << "Skybox" << YAML::BeginMap;
			emitter << YAML::Key << "Front" << YAML::Value << m_skybox.CubemapFiles[Skybox::FRONT];
			emitter << YAML::Key << "Back" << YAML::Value << m_skybox.CubemapFiles[Skybox::BACK];
			emitter << YAML::Key << "Top" << YAML::Value << m_skybox.CubemapFiles[Skybox::TOP];
			emitter << YAML::Key << "Bottom" << YAML::Value << m_skybox.CubemapFiles[Skybox::BOTTOM];
			emitter << YAML::Key << "Left" << YAML::Value << m_skybox.CubemapFiles[Skybox::LEFT];
			emitter << YAML::Key << "Right" << YAML::Value << m_skybox.CubemapFiles[Skybox::RIGHT];
			emitter << YAML::EndMap;
			emitter << YAML::EndMap;
		}
		emitter << YAML::Key << "RenderObjects";
		emitter << YAML::BeginSeq;
		for (uint32_t i = 0; i < GetRenderObjectCount(); ++i)
		{
			const Hierarchy& h = m_hierarchy[i];
			emitter << YAML::BeginMap;
			emitter << YAML::Key << "RenderObject" << YAML::Value << i;
			emitter << YAML::Key << "Name" << YAML::Value << GetRenderObjectName(i);
			emitter << YAML::Key << "Parent" << YAML::Value << h.Parent;

			const TransformComponent& t = m_transformComponents[i];
			emitter << YAML::Key << "TransformComponent" << YAML::BeginMap;
			emitter << YAML::Key << "Position" << YAML::Value << t.Position;
			emitter << YAML::Key << "Rotation" << YAML::Value << t.Rotation;
			emitter << YAML::Key << "Scale" << YAML::Value << t.Scale;
			emitter << YAML::EndMap;

			if (m_lightComponentMap.contains(i))
			{
				const LightComponent& light = m_lightComponentMap[i];
				emitter << YAML::Key << "LightComponent" << YAML::BeginMap;
				emitter << YAML::Key << "Type" << YAML::Value << LightTypeToStr(light.Type);
				emitter << YAML::Key << "Color" << YAML::Value << light.Color;
				emitter << YAML::Key << "Radius" << YAML::Value << light.Radius;
				emitter << YAML::Key << "Compression" << YAML::Value << light.Radius;
				emitter << YAML::Key << "InnerCutoff" << YAML::Value << light.InnerCutoff;
				emitter << YAML::Key << "OuterCutoff" << YAML::Value << light.OuterCutoff;
				emitter << YAML::Key << "ProjectShadows" << YAML::Value << light.ProjectShadows;
				emitter << YAML::EndMap;
			}

			if (m_meshComponentMap.contains(i))
			{
				emitter << YAML::Key << "MeshComponent" << YAML::BeginMap;
				const MeshComponent& mesh = m_meshComponentMap[i];
				emitter << YAML::Key << "MeshAssetPath" << YAML::Value << mesh.MeshAssetPath;
				emitter << YAML::Key << "MeshName" << YAML::Value << mesh.MeshName;
				emitter << YAML::EndMap;
			}

			emitter << YAML::EndMap;
		}
		emitter << YAML::EndSeq;
		emitter << YAML::EndMap;

		check(emitter.good());
		const char* out = emitter.c_str();
		uint32_t size = (uint32_t)emitter.size();
		Logf(LogLevel::Info, "YAML %u b\n%s\n", size, out);

		io::File file;
		check(file.Open(filepath, "w"));
		file.Write(out, size);
		file.Close();
	}

	void Scene::DestroyRenderObject(sRenderObject object)
	{
		check(false && "not implemented yet" && __FUNCTION__ && __FILE__ && __LINE__);
	}

	const MeshComponent* Scene::GetMesh(sRenderObject renderObject) const
	{
		check(IsValid(renderObject));
		const MeshComponent* mesh = nullptr;
		if (m_meshComponentMap.contains(renderObject))
			mesh = &m_meshComponentMap.at(renderObject);
		return mesh;
	}

	void Scene::SetMesh(sRenderObject renderObject, const MeshComponent& meshComponent)
	{
		check(IsValid(renderObject));
		check(meshComponent.MeshIndex < (uint32_t)m_meshes.size());
		m_meshComponentMap[renderObject] = meshComponent;
	}

	const char* Scene::GetRenderObjectName(sRenderObject object) const
	{
		return IsValid(object) ? m_names[object.Id].c_str() : nullptr;
	}

	bool Scene::IsValid(sRenderObject object) const
	{
		return object.Id < (uint32_t)m_hierarchy.size();
	}

	uint32_t Scene::GetRenderObjectCount() const
	{
		return (uint32_t)m_hierarchy.size();
	}

	cMaterial* Scene::CreateMaterial(const char* name)
	{
		check(m_materialArray.size() < MIST_MAX_MATERIALS);
		uint32_t matIndex = (uint32_t)m_materialArray.size();
		m_materialArray.push_back(cMaterial());
		cMaterial& mat = m_materialArray[matIndex];
		mat.SetName(name);
		return &mat;
	}

	cMaterial* Scene::GetMaterial(uint32_t index)
	{
		check(index < (uint32_t)m_materialArray.size());
		return &m_materialArray[index];
	}

	const cMaterial* Scene::GetMaterial(uint32_t index) const
	{
		check(index < (uint32_t)m_materialArray.size());
		return &m_materialArray[index];
	}

	cMaterial* Scene::GetMaterial(const char* name)
	{
		for (uint32_t i = 0; i < (uint32_t)m_materialArray.size(); ++i)
		{
			if (!strcmp(name, m_materialArray[i].GetName()))
				return &m_materialArray[i];
		}
		return nullptr;
	}

	const cMaterial* Scene::GetMaterial(const char* name) const
	{
		return const_cast<Scene*>(this)->GetMaterial(name);
	}

	sRenderObject Scene::GetRoot() const
	{
		static sRenderObject root = 0;
		//for (; m_hierarchy[root].Parent.IsValid(); root = m_hierarchy[root].Parent);
		return root;
	}

	void Scene::SetRenderObjectName(sRenderObject renderObject, const char* name)
	{
		check(IsValid(renderObject));
		m_names[renderObject] = name;
	}

	const TransformComponent& Scene::GetTransform(sRenderObject renderObject) const
	{
		check(IsValid(renderObject));
		return m_transformComponents[renderObject];
	}

	void Scene::SetTransform(sRenderObject renderObject, const TransformComponent& transform)
	{
		check(IsValid(renderObject));
		m_transformComponents[renderObject] = transform;
		MarkAsDirty(renderObject);
	}

	const LightComponent* Scene::GetLight(sRenderObject renderObject) const
	{
		check(IsValid(renderObject));
		const LightComponent* light = nullptr;
		if (m_lightComponentMap.contains(renderObject))
			light = &m_lightComponentMap.at(renderObject);
		return light;
	}

	void Scene::SetLight(sRenderObject renderObject, const LightComponent& light)
	{
		check(IsValid(renderObject));
		m_lightComponentMap[renderObject] = light;
	}

	void Scene::MarkAsDirty(sRenderObject renderObject)
	{
		check(IsValid(renderObject));
		int32_t level = m_hierarchy[renderObject].Level;
		m_dirtyNodes[level].push_back(renderObject);
		for (sRenderObject child = m_hierarchy[renderObject].Child; child.IsValid(); child = m_hierarchy[child].Sibling)
			MarkAsDirty(child);
	}


	void Scene::RecalculateTransforms()
	{
		check(m_localTransforms.size() == m_transformComponents.size());
		check(m_globalTransforms.size() == m_transformComponents.size());
		TransformComponentToMatrix(m_transformComponents.data(), m_localTransforms.data(), (uint32_t)m_transformComponents.size());
		// Process root level first
		if (!m_dirtyNodes[0].empty())
		{
			for (uint32_t i = 0; i < m_dirtyNodes[0].size(); ++i)
			{
				uint32_t nodeIndex = m_dirtyNodes[0][i];
				m_globalTransforms[nodeIndex] = m_localTransforms[nodeIndex];
			}
			m_dirtyNodes[0].clear();
		}
		// Iterate over the deeper levels
		for (uint32_t level = 1; level < MaxNodeLevel; ++level)
		{
			for (uint32_t nodeIndex = 0; nodeIndex < m_dirtyNodes[level].size(); ++nodeIndex)
			{
				int32_t node = m_dirtyNodes[level][nodeIndex];
				int32_t parentNode = m_hierarchy[node].Parent;
				m_globalTransforms[node] = m_globalTransforms[parentNode] * m_localTransforms[node];
			}
			m_dirtyNodes[level].clear();
		}
	}

	bool Scene::LoadMeshesFromFile(const RenderContext& context, const char* filepath)
	{
		PROFILE_SCOPE_LOG(LoadMeshes, __FUNCTION__);
		cgltf_data* data = gltf_api::ParseFile(filepath);
		char rootAssetPath[512];
		io::GetDirectoryFromFilepath(filepath, rootAssetPath, 512);
		if (!data)
		{
			Logf(LogLevel::Error, "Cannot open file to load scene model: %s.\n", filepath);
			return false;
		}

		for (uint32_t i = 0; i < data->materials_count; ++i)
		{
			cMaterial* m = CreateMaterial(data->materials[i].name);
			gltf_api::LoadMaterial(*m, context, data->materials[i], rootAssetPath);
		}

		uint32_t nodesCount = (uint32_t)data->nodes_count;
		uint32_t renderObjectOffset = GetRenderObjectCount();

		tDynArray<Vertex> tempVertices;
		tDynArray<uint32_t> tempIndices;
		for (uint32_t i = 0; i < nodesCount; ++i)
		{
			const cgltf_node& node = data->nodes[i];

			// Process mesh
			if (node.mesh)
			{
				m_meshes.push_back(cMesh());
				cMesh& mesh = m_meshes.back();
				mesh.SetName(node.mesh->name);
				tDynArray<PrimitiveMeshData>& primitives = mesh.PrimitiveArray;
				tempVertices.clear();
				tempIndices.clear();
				primitives.resize(node.mesh->primitives_count);
				for (uint32_t j = 0; j < node.mesh->primitives_count; ++j)
				{
					const cgltf_primitive& cgltfprimitive = node.mesh->primitives[j];
					PrimitiveMeshData& primitive = primitives[j];
					check(cgltfprimitive.type == cgltf_primitive_type_triangles);
					check(cgltfprimitive.indices && cgltfprimitive.indices->type == cgltf_type_scalar && cgltfprimitive.indices->count % 3 == 0);
					check(cgltfprimitive.attributes && cgltfprimitive.attributes->data);

					uint32_t indexCount = cgltfprimitive.indices->count;
					uint32_t vertexCount = cgltfprimitive.attributes[0].data->count;
					uint32_t vertexOffset = (uint32_t)tempVertices.size();
					uint32_t indexOffset = (uint32_t)tempIndices.size();
					tempIndices.resize(indexOffset + cgltfprimitive.indices->count);
					tempVertices.resize(vertexOffset + vertexCount);

					primitive.FirstIndex = indexOffset;
					primitive.Count = indexCount;

					gltf_api::LoadIndices(cgltfprimitive, tempIndices.data() + indexOffset, vertexOffset);
					gltf_api::LoadVertices(cgltfprimitive, tempVertices.data() + vertexOffset, vertexCount);

					cMaterial* material = GetMaterial(cgltfprimitive.material->name);
					check(material);
					primitive.Material = material;

					check(cgltfprimitive.indices->count == primitive.Count);
				}

				mesh.SetupVertexBuffer(context, tempVertices.data(), sizeof(Vertex) * (uint32_t)tempVertices.size());
				mesh.SetupIndexBuffer(context, tempIndices.data(), (uint32_t)tempIndices.size());

				char buff[256];
				GetResourceFileId(filepath, node.mesh->name, buff);
				check(!m_meshNameIndexMap.contains(buff));
				m_meshNameIndexMap[buff] = m_meshes.size() - 1;
			}
		}
		tempVertices.clear();
		tempVertices.shrink_to_fit();
		tempIndices.clear();
		tempIndices.shrink_to_fit();
		gltf_api::FreeData(data);
		return true;
	}

	bool Scene::LoadSkybox(const RenderContext& context, Skybox& skybox, const char* front, const char* back, const char* left, const char* right, const char* top, const char* bottom)
	{
		// descriptors generator
		DescriptorBuilder builder = DescriptorBuilder::Create(*context.LayoutCache, *context.DescAllocator);

		// Load textures from files
		const char* files[] = { left, right, top, bottom, front, back };
		io::TextureRaw textureData[Skybox::COUNT];
		for (uint32_t i = 0; i < Skybox::COUNT; ++i)
			check(io::LoadTexture(files[i], textureData[i]));
		// Size integrity check and generate an array to reference the pixels of each texture.
		const uint8_t* pixelsArray[Skybox::COUNT];
		for (uint32_t i = 0; i < Skybox::COUNT; ++i)
		{
			check(*files[i]);
			strcpy_s(skybox.CubemapFiles[i], files[i]);
			check(textureData[i].Width == textureData[(i + 1) % Skybox::COUNT].Width
				&& textureData[i].Height == textureData[(i + 1) % Skybox::COUNT].Height
				&& textureData[i].Channels == textureData[(i + 1) % Skybox::COUNT].Channels
				&& textureData[i].Pixels);
			pixelsArray[i] = textureData[i].Pixels;
		}

		// Create texture
		tImageDescription imageDesc;
		imageDesc.Format = FORMAT_R8G8B8A8_SRGB;
		imageDesc.Layers = Skybox::COUNT;
		imageDesc.Width = textureData[0].Width;
		imageDesc.Height = textureData[0].Height;
		imageDesc.Depth = 1;
		imageDesc.Flags = VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT;
		imageDesc.MipLevels = 1; // needs cubemap?
		imageDesc.SampleCount = SAMPLE_COUNT_1_BIT;
		Texture* cubemapTex = Texture::Create(context, imageDesc);
		// Set image layers with each cubemap texture
		cubemapTex->SetImageLayers(context, pixelsArray, Skybox::COUNT);
		//SubmitTexture(cubemapTex);

		tViewDescription viewDesc;
		viewDesc.BaseArrayLayer = 0;
		viewDesc.LayerCount = Skybox::COUNT;
		viewDesc.ViewType = VK_IMAGE_VIEW_TYPE_CUBE;
		VkDescriptorImageInfo info;
		info.imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
		info.imageView = cubemapTex->CreateView(context, viewDesc);
		info.sampler = cubemapTex->GetSampler();
		builder.BindImage(0, &info, 1, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, VK_SHADER_STAGE_FRAGMENT_BIT);
		check(builder.Build(context, skybox.CubemapSet));

		// Mesh
		static const char* cubeMeshFile = ASSET_PATH("models/cube.gltf");
		if (!m_meshNameIndexMap.contains(cubeMeshFile))
			LoadMeshesFromFile(context, cubeMeshFile);
		skybox.MeshIndex = UINT32_MAX;
		check(m_meshNameIndexMap.contains(ASSET_PATH("models/cube.gltf|cube")));
		skybox.MeshIndex = m_meshNameIndexMap["models/cube.gltf|cube"];
		check(skybox.MeshIndex < (uint32_t)m_meshes.size());

		return true;
	}

	const cMesh* Scene::GetMeshArray() const
	{
		return m_meshes.data();
	}

	uint32_t Scene::GetMeshCount() const
	{
		return (uint32_t)m_meshes.size();
	}

	const cMesh* Scene::GetMeshRenderData(const char* meshId) const
	{
		return const_cast<Scene*>(this)->GetMeshRenderData(meshId);
	}

	cMesh* Scene::GetMeshRenderData(const char* meshId)
	{
		if (m_meshNameIndexMap.contains(meshId))
		{
			check(m_meshNameIndexMap.at(meshId) < m_meshes.size());
			return &m_meshes[m_meshNameIndexMap.at(meshId)];
		}
		return nullptr;
	}

	const cMesh* Scene::GetMeshRenderData(const char* file, const char* meshname) const
	{
		char buff[256];
		GetResourceFileId(file, meshname, buff);
		return GetMeshRenderData(buff);
	}

	cMesh* Scene::GetMeshRenderData(const char* file, const char* meshname)
	{
		char buff[256];
		GetResourceFileId(file, meshname, buff);
		return GetMeshRenderData(buff);
	}

	const cMaterial* Scene::GetMaterialArray() const
	{
		return m_materialArray.data();
	}

	uint32_t Scene::GetMaterialCount() const
	{
		return (uint32_t)m_materialArray.size();
	}

	void Scene::Draw(const RenderContext& context, ShaderProgram* shader, uint32_t materialSetIndex, uint32_t modelSetIndex, VkDescriptorSet modelSet) const
	{
		CPU_PROFILE_SCOPE(Scene_Draw);
		VkCommandBuffer cmd = context.GetFrameContext().GraphicsCommandContext.CommandBuffer;
		// Iterate scene graph to render models.
		const cMaterial* lastMaterial = nullptr;
		const cMesh* lastMesh = nullptr;
		uint32_t nodeCount = GetRenderObjectCount();
		for (uint32_t i = 0; i < nodeCount; ++i)
		{
			sRenderObject renderObject = i;
			const MeshComponent* meshComponent = GetMesh(renderObject);
			if (meshComponent)
			{
				check(meshComponent->MeshIndex < (uint32_t)m_meshes.size());
				const cMesh* mesh = &m_meshes[meshComponent->MeshIndex];

				// BaseOffset in buffer is already setted when descriptor was created.
				uint32_t modelDynamicOffset = i * sizeof(glm::mat4);
				shader->SetDynamicBufferOffset(context, "u_model", modelDynamicOffset);

				// Bind vertex/index buffers just if needed
				if (lastMesh != mesh)
				{
					lastMesh = mesh;
					mesh->BindBuffers(cmd);
				}
				// Iterate primitives of current mesh
				for (uint32_t j = 0; j < (uint32_t)mesh->PrimitiveArray.size(); ++j)
				{
					const PrimitiveMeshData& drawData = mesh->PrimitiveArray[j];
					// TODO: material by default if there is no material.
					if (lastMaterial != drawData.Material)
					{
						lastMaterial = drawData.Material;
						drawData.Material->BindTextures(context, *shader, materialSetIndex);
					}
					shader->FlushDescriptors(context);
					RenderAPI::CmdDrawIndexed(cmd, drawData.Count, 1, drawData.FirstIndex, 0, 0);
				}
			}
		}
	}

	void Scene::Draw(const RenderContext& context, ShaderProgram* shader, uint32_t modelSetIndex, VkDescriptorSet modelSet) const
	{
		VkCommandBuffer cmd = context.GetFrameContext().GraphicsCommandContext.CommandBuffer;
		CPU_PROFILE_SCOPE(Scene_Draw);
		// Iterate scene graph to render models.
		const cMaterial* lastMaterial = nullptr;
		const cMesh* lastMesh = nullptr;
		uint32_t nodeCount = GetRenderObjectCount();
		for (uint32_t i = 0; i < nodeCount; ++i)
		{
			sRenderObject renderObject = i;
			const MeshComponent* meshComponent = GetMesh(renderObject);
			if (meshComponent)
			{
				check(meshComponent->MeshIndex < (uint32_t)m_meshes.size());
				const cMesh* mesh = &m_meshes[meshComponent->MeshIndex];

				// BaseOffset in buffer is already setted when descriptor was created.
				uint32_t modelDynamicOffset = i * sizeof(glm::mat4);
				shader->SetDynamicBufferOffset(context, "u_model", modelDynamicOffset);

				// Bind vertex/index buffers just if needed
				if (lastMesh != mesh)
				{
					lastMesh = mesh;
					mesh->BindBuffers(cmd);
				}
				shader->FlushDescriptors(context);

				RenderAPI::CmdDrawIndexed(cmd, mesh->IndexCount, 1, 0, 0, 0);
			}
		}
	}

	void Scene::DrawSkybox(CommandBuffer cmd, ShaderProgram* shader)
	{
		if (m_skybox.CubemapSet != VK_NULL_HANDLE)
		{
			const cMesh& mesh = m_meshes[m_skybox.MeshIndex];
			mesh.BindBuffers(cmd);
			shader->BindDescriptorSets(cmd, &m_skybox.CubemapSet, 1, 1, nullptr, 0);
			RenderAPI::CmdDrawIndexed(cmd, mesh.IndexCount, 1, 0, 0, 0);
		}
	}

	void Scene::ImGuiDraw()
	{
		ImGui::Begin("SceneGraph");

		float posStep = 0.5f;
		float rotStep = 0.1f;
		float sclStep = 0.5f;

		static char sceneFile[256];
		static bool _b = false;
		if (!_b)
		{
			strcpy_s(sceneFile, "scenes/Scene.yaml");
			_b = !false;
		}
		const RenderContext& context = m_engine->GetContext();
		ImGui::Columns(3);
		if (ImGui::Button("Save"))
			SaveScene(context, sceneFile);
		ImGui::NextColumn();
		if (ImGui::Button("Load"))
			LoadScene(context, sceneFile);
		ImGui::NextColumn();
		ImGui::InputText("Scene file", sceneFile, 256);
		ImGui::Columns();

		ImGui::Separator();
		ImGui::Text("Environment");
		ImGui::ColorEdit3("Ambient color", &m_ambientColor[0]);
		ImGui::Button("Reload");

		ImGui::Separator();
		if (ImGui::TreeNode("Scene tree"))
		{
			for (uint32_t i = 0; i < GetRenderObjectCount(); ++i)
			{
				char treeId[2];
				sprintf(treeId, "%u", i);
				if (ImGui::TreeNode(treeId, "%s", GetRenderObjectName(i)))
				{
					glm::mat4 transform;
					TransformComponentToMatrix(&m_transformComponents[i], &transform, 1);
					DebugRender::DrawAxis(transform);
					const Hierarchy& node = m_hierarchy[i];
					ImGui::Text("Parent: %s", node.Parent != UINT32_MAX ? GetRenderObjectName(node.Parent) : "None");
					char buff[32];
					sprintf_s(buff, "##TransformComponent%u", i);
					if (ImGui::TreeNode(buff, "Transform component"))
					{
						TransformComponent& t = m_transformComponents[i];
						ImGui::Columns(2);
						ImGui::Text("Position");
						ImGui::NextColumn();
						sprintf_s(buff, "##TransformPos%d", i);
						bool dirty = ImGui::DragFloat3(buff, &t.Position[0], posStep);
						ImGui::NextColumn();
						ImGui::Text("Rotation");
						ImGui::NextColumn();
						sprintf_s(buff, "##TransformRot%d", i);
						dirty |= ImGui::DragFloat3(buff, &t.Rotation[0], rotStep);
						ImGui::NextColumn();
						ImGui::Text("Scale");
						ImGui::NextColumn();
						sprintf_s(buff, "##TransformScl%d", i);
						dirty |= ImGui::DragFloat3(buff, &t.Scale[0], sclStep);
						ImGui::Columns();
						ImGui::TreePop();

						if (dirty)
							MarkAsDirty(i);
					}
					sprintf_s(buff, "##LightComponent%u", i);
					if (m_lightComponentMap.contains(i))
					{
						if (ImGui::TreeNode(buff, "Light component"))
						{
							LightComponent& light = m_lightComponentMap[i];
							static const char* lightTypes[] = { "Point", "Directional", "Spot" };
							uint32_t lightCount = sizeof(lightTypes) / sizeof(const char*);
							if (ImGui::BeginCombo("Type", lightTypes[(uint32_t)light.Type]))
							{
								for (uint32_t j = 0; j < lightCount; ++j)
								{
									if (ImGui::Selectable(lightTypes[j], j == (uint32_t)light.Type))
										light.Type = (ELightType)j;
								}
								ImGui::EndCombo();
							}
							ImGui::Columns(2);
							ImGui::Text("Color");
							ImGui::NextColumn();
							sprintf_s(buff, "##LightColor%u", i);
							ImGui::ColorEdit3(buff, &light.Color[0]);
							ImGui::NextColumn();
							ImGui::Text("Radius");
							ImGui::NextColumn();
							sprintf_s(buff, "##LightRadius%u", i);
							ImGui::DragFloat(buff, &light.Radius, 0.5f, 0.f, FLT_MAX);
							ImGui::NextColumn();
							ImGui::Text("Compression");
							sprintf_s(buff, "##LightCompression%u", i);
							ImGui::NextColumn();
							ImGui::DragFloat(buff, &light.Compression, 0.05f, 0.f, FLT_MAX);
							ImGui::NextColumn();
							ImGui::Text("Inner cutoff");
							ImGui::NextColumn();
							sprintf_s(buff, "##LightInnerCutoff%u", i);
							ImGui::DragFloat(buff, &light.InnerCutoff, 0.1f, 0.f, FLT_MAX);
							ImGui::NextColumn();
							ImGui::Text("Outer cutoff");
							ImGui::NextColumn();
							sprintf_s(buff, "##LightOuterCutoff%u", i);
							ImGui::DragFloat(buff, &light.OuterCutoff, 0.1f, 0.f, FLT_MAX);
							ImGui::NextColumn();
							ImGui::Text("Project shadows");
							ImGui::NextColumn();
							sprintf_s(buff, "##LightShadows%u", i);
							ImGui::Checkbox(buff, &light.ProjectShadows);
							ImGui::NextColumn();

							ImGui::Columns();
							ImGui::TreePop();
						}
					}

					ImGui::TreePop();
				}
			}
			ImGui::TreePop();
		}
		if (ImGui::TreeNode("Material list"))
		{
			char buff[32];
			for (uint32_t i = 0; i < (uint32_t)m_materialArray.size(); ++i)
			{
				if (ImGui::TreeNode(&m_materialArray[i], "(Slot %d) %s", i, m_materialArray[i].GetName()))
				{
#if 0
					bool dirty = false;
					sprintf_s(buff, "##Metallic_%d", i);
					float metallic = m_materialArray[i].GetMetallic();
					dirty |= ImGui::DragFloat(buff, &metallic, 0.01f, 0.f, 1.f);
					sprintf_s(buff, "##Roughness_%d", i);
					float roughness = m_materialArray[i].GetMetallic();
					dirty |= ImGui::DragFloat(buff, &roughness, 0.01f, 0.f, 1.f);
					if (dirty)
					{
						m_materialArray[i].SetMetallic(metallic);
						m_materialArray[i].SetRoughness(roughness);
					}
#endif // 0

					ImGui::TreePop();
				}
			}
			ImGui::TreePop();
		}
		ImGui::End();
	}

	bool Scene::IsDirty() const
	{
		for (uint32_t i = 0; i < MaxNodeLevel; ++i)
		{
			if (!m_dirtyNodes[i].empty())
				return true;
		}
		return false;
	}

	void Scene::UpdateRenderData(const RenderContext& renderContext, RenderFrameContext& frameContext)
	{
		if (GetRenderObjectCount())
		{
			// Update geometry
			RecalculateTransforms();
			check(!IsDirty());
			const glm::mat4& viewMat = frameContext.CameraData->InvView;
			ProcessEnvironmentData(viewMat, m_environmentData);

			UniformBufferMemoryPool* buffer = &frameContext.GlobalBuffer;
			check(buffer->SetUniform(renderContext, UNIFORM_ID_SCENE_ENV_DATA, &m_environmentData, sizeof(EnvironmentData)));
			//check(buffer->SetUniform(renderContext, UNIFORM_ID_SCENE_MODEL_TRANSFORM_ARRAY, GetRawGlobalTransforms(), GetRenderObjectCount() * sizeof(glm::mat4)));
			check(buffer->SetDynamicUniform(renderContext, UNIFORM_ID_SCENE_MODEL_TRANSFORM_ARRAY, GetRawGlobalTransforms(), GetRenderObjectCount(), sizeof(glm::mat4), 0));

#if 0
			// Update materials
			tArray<MaterialUniform, MIST_MAX_MATERIALS> materialUniformBuffer;
			check((uint32_t)m_materialArray.size() <= MIST_MAX_MATERIALS);
			for (uint32_t i = 0; i < (uint32_t)m_materialArray.size(); ++i)
			{
				//check(m_dirtyMaterials[i] < (uint32_t)m_materialArray.size());
				Material& material = m_materialArray[i];
				//if (material.IsDirty())
				{
					RenderHandle h = material.GetHandle();
					MaterialRenderData& mrd = m_materialRenderDataArray[h];
					//if (material.IsDirty())
					{
						auto submitTexture = [&](RenderHandle texHandle, uint32_t binding, uint32_t arrayIndex)
							{
								Texture* texture;
								if (texHandle.IsValid())
								{
									texture = m_renderData.Textures[texHandle];
								}
								else
								{
									RenderHandle defTex = m_engine->GetDefaultTexture();
									texture = m_renderData.Textures[defTex];
								}
								BindDescriptorTexture(m_engine->GetContext(), texture, mrd.MaterialSets[frameContext.FrameIndex].TextureSet, binding, arrayIndex);
								mrd.Textures[arrayIndex] = texture;
							};
						submitTexture(material.GetAlbedoTexture(), 0, 0);
						submitTexture(material.GetNormalTexture(), 0, 1);
						submitTexture(material.GetSpecularTexture(), 0, 2);
						submitTexture(material.GetOcclusionTexture(), 0, 3);
						submitTexture(material.GetMetallicTexture(), 0, 4);
						submitTexture(material.GetRoughnessTexture(), 0, 5);
					}

					check(i < MIST_MAX_MATERIALS);
					materialUniformBuffer[i].Metallic = material.GetMetallic();
					materialUniformBuffer[i].Roughness = material.GetRoughness();
					
					material.SetDirty(false);
				}
			}
			buffer->SetDynamicUniform(renderContext, "Material", materialUniformBuffer.data(), MIST_MAX_MATERIALS, sizeof(MaterialUniform), 0);

			// Integrity check
			for (uint32_t i = 0; i < (uint32_t)m_materialArray.size(); ++i)
			{
				check(!m_materialArray[i].IsDirty());
			}
#endif
		}
	}

	const glm::mat4* Scene::GetRawGlobalTransforms() const
	{
		check(!IsDirty());
		return m_globalTransforms.data();
	}

	void Scene::ProcessEnvironmentData(const glm::mat4& viewSpace, EnvironmentData& environmentData)
	{
		environmentData.ViewPosition = math::GetPos(glm::inverse(viewSpace));
#if 1
		environmentData.AmbientColor = m_ambientColor;
		environmentData.ActiveLightsCount = 0.f;
		environmentData.ActiveSpotLightsCount = 0.f;
		uint32_t shadowMapIndex = 0;
		for (uint32_t i = 0; i < GetRenderObjectCount(); ++i)
		{
			if (m_lightComponentMap.contains(i))
			{
				const glm::mat4& mat = m_globalTransforms[i];
				const glm::vec3 pos = math::GetPos(viewSpace * mat);
				const glm::vec3 dir = math::GetDir(viewSpace * mat);
				const LightComponent& light = m_lightComponentMap[i];
				switch (light.Type)
				{
				case ELightType::Point:
					environmentData.Lights[(uint32_t)environmentData.ActiveLightsCount].Color = light.Color;
					environmentData.Lights[(uint32_t)environmentData.ActiveLightsCount].Compression = light.Compression;
					environmentData.Lights[(uint32_t)environmentData.ActiveLightsCount].Position = pos;
					environmentData.Lights[(uint32_t)environmentData.ActiveLightsCount].Radius = light.Radius;
					++environmentData.ActiveLightsCount;
					break;
				case ELightType::Directional:
					environmentData.DirectionalLight.Color = light.Color;
					environmentData.DirectionalLight.ShadowMapIndex = light.ProjectShadows ? (float)shadowMapIndex++ : -1.f;
					environmentData.DirectionalLight.Direction = dir;
					break;
				case ELightType::Spot:
					environmentData.SpotLights[(uint32_t)environmentData.ActiveSpotLightsCount].Color = light.Color;
					environmentData.SpotLights[(uint32_t)environmentData.ActiveSpotLightsCount].ShadowMapIndex = light.ProjectShadows ? (float)shadowMapIndex++ : -1.f;
					environmentData.SpotLights[(uint32_t)environmentData.ActiveSpotLightsCount].Position = pos;
					environmentData.SpotLights[(uint32_t)environmentData.ActiveSpotLightsCount].Direction = dir;
					environmentData.SpotLights[(uint32_t)environmentData.ActiveSpotLightsCount].InnerCutoff = light.InnerCutoff;
					environmentData.SpotLights[(uint32_t)environmentData.ActiveSpotLightsCount].OuterCutoff = light.OuterCutoff;
					++environmentData.ActiveSpotLightsCount;
					break;
				}
			}
		}
		check(shadowMapIndex <= globals::MaxShadowMapAttachments);
#endif // 0

	}
}

