// Autogenerated code for Mist project
// Source file
#include "Scene.h"
#include "Core/Logger.h"
#include "Core/Debug.h"

#include "RenderSystem/RenderSystem.h"
#include "RenderSystem/TextureLoader.h"



#ifdef MIST_MEM_MANAGEMENT
// TODO: wtf windows declare these macros and project does not compile when MIST_MEM_MANAGEMENT is defined. WTF!?
#undef min
#undef max  
#endif // MIST_MEM_MANAGEMENT

#include <glm/gtx/transform.hpp>
#include <glm/gtx/quaternion.hpp>
#include <glm/gtx/euler_angles.hpp>
#include <glm/fwd.hpp>
#include "Render/Mesh.h"
#include "Utils/GenericUtils.h"
#include "Render/VulkanRenderEngine.h"
#include "Render/DebugRender.h"
#include <algorithm>
#include <imgui.h>

#define SCENE_LOAD_YAML
#ifdef SCENE_LOAD_YAML

#include <yaml-cpp/yaml.h>

#endif // SCENE_LOAD_YAML
#include <fstream>
#include "Core/SystemMemory.h"
#include "Utils/TimeUtils.h"
#include "Render/Model.h"
#include "Utils/FileSystem.h"
#include "Render/RendererBase.h"
#include "Render/RenderProcesses/ShadowMap.h"
#include "Render/RenderProcesses/Preprocesses.h"

//#define MIST_ENABLE_LOADER_LOG

#ifdef SCENE_LOAD_YAML
YAML::Emitter& operator<<(YAML::Emitter& e, const glm::vec3& v)
{
	e << YAML::Flow << YAML::BeginSeq << v.x << v.y << v.z << YAML::EndSeq;
	return e;
}

YAML::Emitter& operator<<(YAML::Emitter& e, const glm::vec4& v)
{
	e << YAML::Flow << YAML::BeginSeq << v.x << v.y << v.z << v.w << YAML::EndSeq;
	return e;
}

YAML::Emitter& operator<<(YAML::Emitter& e, const Mist::tAngles& a)
{
	e << YAML::Flow << YAML::BeginSeq << a.m_pitch << a.m_yaw << a.m_roll << YAML::EndSeq;
	return e;
}


namespace YAML
{
	template<>
	struct convert<glm::vec2>
	{
		static Node encode(const glm::vec2& rhs)
		{
			Node node;
			node.push_back(rhs.x);
			node.push_back(rhs.y);
			return node;
		}

		static bool decode(const Node& node, glm::vec2& rhs)
		{
			if (!node.IsSequence() || node.size() != 2)
				return false;

			rhs.x = node[0].as<float>();
			rhs.y = node[1].as<float>();
			return true;
		}
	};

	template<>
	struct convert<glm::vec3>
	{
		static Node encode(const glm::vec3& rhs)
		{
			Node node;
			node.push_back(rhs.x);
			node.push_back(rhs.y);
			node.push_back(rhs.z);
			return node;
		}

		static bool decode(const Node& node, glm::vec3& rhs)
		{
			if (!node.IsSequence() || node.size() != 3)
				return false;

			rhs.x = node[0].as<float>();
			rhs.y = node[1].as<float>();
			rhs.z = node[2].as<float>();
			return true;
		}
	};

	template<>
	struct convert<Mist::tAngles>
	{
		static Node encode(const Mist::tAngles& rhs)
		{
			Node node;
			node.push_back(rhs.m_pitch);
			node.push_back(rhs.m_yaw);
			node.push_back(rhs.m_roll);
			return node;
		}

		static bool decode(const Node& node, Mist::tAngles& rhs)
		{
			if (!node.IsSequence() || node.size() != 3)
				return false;

			rhs.m_pitch = node[0].as<float>();
			rhs.m_yaw = node[1].as<float>();
			rhs.m_roll = node[2].as<float>();
			return true;
		}
	};
}

#endif


namespace Mist
{
	CIntVar CVar_DebugCubes("r_debugCubes", 0);
	CStrVar CVar_RenderInclude("r_renderInclude", "");
	CStrVar CVar_RenderExclude("r_renderExclude", "");
	CStrVar CVar_ShowAABBMeshName("r_showAABBMeshName", "");

	SceneRenderer* g_sceneRenderer = nullptr;

	bool SceneFilter(const char* name)
	{
		if (*CVar_RenderInclude.Get() && !WildStricmp(CVar_RenderInclude.Get(), name))
			return false;
		if (*CVar_RenderExclude.Get() && WildStricmp(CVar_RenderExclude.Get(), name))
			return false;
		return true;
	}

	const char* LightTypeToStr(ELightType e)
	{
		switch (e)
		{
		case ELightType::Point: return "Point";
		case ELightType::Directional: return "Directional";
		case ELightType::Spot: return "Spot";
		}
		check(false);
		return nullptr;
	}

	ELightType StrToLightType(const char* str)
	{
		if (!strcmp(str, "Point")) return ELightType::Point;
		if (!strcmp(str, "Spot")) return ELightType::Spot;
		if (!strcmp(str, "Directional")) return ELightType::Directional;
		check(false);
		return (ELightType)0xff;
	}

	void TransformComponentToMatrix(const TransformComponent* transforms, glm::mat4* matrices, uint32_t count)
	{
		for (uint32_t i = 0; i < count; ++i)
			matrices[i] = math::ToMat4(transforms[i].Position, transforms[i].Rotation, transforms[i].Scale);
	}

	template <uint32_t N>
	void GetResourceFileId(const char* file, const char* resname, char(&buff)[N])
	{
		sprintf_s(buff, "%s|%s", file, resname);
	}

	EnvironmentData::EnvironmentData()
	{
		ZeroMem(this, sizeof(*this));
		ambientColor = { 0.02f, 0.02f, 0.02f };
	}

	Scene::Scene(IRenderEngine* engine) : m_engine(static_cast<VulkanRenderEngine*>(engine))
	{
		m_irradianceRequestInfo = _new PreprocessIrradianceInfo();
		m_irradianceRequestInfo->cubemapWidthHeight = 1024;
		m_irradianceRequestInfo->irradianceCubemapWidthHeight = 32;
		m_irradianceRequestInfo->specularCubemapWidthHeight = 128;
		m_irradianceRequestInfo->minCubemapClamp = glm::vec3(0.f);
		m_irradianceRequestInfo->maxCubemapClamp = glm::vec3(2.f);
		//m_irradianceRequestInfo->hdrFilepath = "textures/flamingo_pan_4k.hdr";
		m_irradianceRequestInfo->hdrFilepath = "textures/citrus_orchard_road_puresky_4k.hdr";
		//m_irradianceRequestInfo->hdrFilepath = "textures/climbing_gym_4k.hdr";
		m_irradianceRequestInfo->userData = this;
	}

	Scene::~Scene()
	{
		delete m_irradianceRequestInfo;
		m_irradianceRequestInfo = nullptr;
	}

	void Scene::Init()
	{
		m_globalTransforms.AllocateAndResize(globals::MaxRenderObjects);
		m_localTransforms.AllocateAndResize(globals::MaxRenderObjects);
		m_renderTransforms.AllocateAndResize(globals::MaxRenderObjects);
		m_transformComponents.AllocateAndResize(globals::MaxRenderObjects);
		m_names.Allocate(globals::MaxRenderObjects);
		m_hierarchy.Allocate(globals::MaxRenderObjects);
		for (uint32_t i = 0; i < MaxNodeLevel; ++i)
			m_dirtyNodes[i].Allocate(globals::MaxRenderObjects);
	}

	void Scene::Destroy()
	{
		for (uint32_t i = 0; i < m_models.GetSize(); ++i)
			m_models[i].Destroy();
		m_models.Clear();
		m_localTransforms.Delete();
		m_globalTransforms.Delete();
		m_hierarchy.Delete();
		m_names.Delete();
		for (uint32_t i = 0; i < MaxNodeLevel; ++i)
			m_dirtyNodes[i].Delete();
	}

	void Scene::Tick(float deltaTime)
	{
		check(m_cameraIndex <m_cameras.GetSize());
		CameraController& c = GetCamera();
		c.Tick(deltaTime);
		m_engine->UpdateSceneView(c.GetCamera().GetView(), c.GetCamera().GetProjection());
	}

	const CameraController& Scene::GetCamera() const
	{
		check(m_cameraIndex <m_cameras.GetSize());
		return m_cameras[m_cameraIndex];
	}

	CameraController& Scene::GetCamera()
	{
		check(m_cameraIndex <m_cameras.GetSize());
		return m_cameras[m_cameraIndex];
	}

	sRenderObject Scene::CreateRenderObject(sRenderObject parent)
	{
		// Generate new node in all basics structures
		sRenderObject node = m_hierarchy.GetSize();
		m_localTransforms[node] = glm::mat4(1.f);
		m_globalTransforms[node] = glm::mat4(1.f);
		m_transformComponents[node] = { .Position = glm::vec3(0.f), .Rotation = tAngles(0.f), .Scale = glm::vec3(1.f) };
		char buff[64];
		sprintf_s(buff, "RenderObject_%u", node.Id);
		m_names.Push(buff);
		m_hierarchy.Push({ .Parent = parent });

		// Connect siblings
		if (parent.IsValid())
		{
			check(parent.Id < m_hierarchy.GetSize());
			sRenderObject firstSibling = m_hierarchy[parent].Child;
			if (firstSibling.IsValid())
			{
				sRenderObject sibling;
				for (sibling = firstSibling; m_hierarchy[sibling].Sibling.IsValid(); sibling = m_hierarchy[sibling].Sibling);
				m_hierarchy[sibling].Sibling = node;
			}
			else
			{
				m_hierarchy[parent].Child = node;
			}
		}

		m_hierarchy[node].Level = parent.IsValid() ? m_hierarchy[parent].Level + 1 : 0;
		m_hierarchy[node].Child = index_invalid;
		m_hierarchy[node].Sibling = index_invalid;
		return node;
	}

	index_t Scene::LoadModel(const char* filepath)
	{
		cModel* model = GetModel(filepath);
		if (!model)
		{
			m_models.Push();
			model = &m_models.GetBack();
			check(model->LoadModel(g_device, filepath));
		}
		check(model);
		return (index_t)(model-m_models.GetData());
	}

	void Scene::ImGuiDrawModel(const cModel* model, const glm::mat4& transform)
	{
		auto textAABBFn = [](const AABB_t& bb)
			{
				ImGui::Text("Bounding box [{%.3f, %.3f, %.3f}, {%.3f, %.3f, %.3f}]",
					bb.min.x, bb.min.x, bb.min.x,
					bb.max.x, bb.max.x, bb.max.x);
			};
		if (ImGui::TreeNode("Model tree"))
		{
			AABB_t aabb = model->GetAABB().ApplyTransform(transform);
			textAABBFn(aabb);
			DebugRender::DrawBox(aabb.min, aabb.max, { 0,1,0 });
			if (ImGui::Button("Dump info"))
				model->DumpInfo();
			ImGui::PushID(model->GetName());
			for (index_t i = 0; i < model->GetTransformsCount(); ++i)
			{
				const cModel::sNode& node = *model->GetNode(i);
				ImGui::PushID(i);
				if (ImGui::TreeNode(model->GetNodeName(i)))
				{
					if (node.MeshId != index_invalid)
					{
						const cMesh& mesh = model->GetMesh(node.MeshId);
						if (ImGui::TreeNode(mesh.GetName()))
						{
							AABB_t aabb = mesh.GetAABB().ApplyTransform(transform);
							DebugRender::DrawBox(aabb.min, aabb.max, glm::vec3(1, 1, 0));
							textAABBFn(aabb);

							ImGui::SeparatorText("Info");
							ImGui::Text("Primitives: %5d", mesh.GetPrimitiveCount());
							ImGui::Text("Triangles:  %5d", mesh.GetIndexCount() / 3);
							ImGui::Text("Gpu memory: %5.2f KB", (float)mesh.GetIndexCount() / 3.f * sizeof(Vertex) / 1024.f);
							ImGui::SeparatorText("Control");

							if (ImGui::TreeNode("Primitives"))
							{
								for (index_t j = 0; j < mesh.GetPrimitiveCount(); ++j)
								{
									const PrimitiveMeshData& primitive = mesh.GetPrimitiveArray()[j];
									aabb = primitive.AABB.ApplyTransform(transform);
									DebugRender::DrawBox(aabb.min, aabb.max, glm::vec3(1, 1, 0));
									textAABBFn(aabb);
									ImGui::SeparatorText("Info");
									ImGui::Text("Material:   %s", primitive.Material ? primitive.Material->GetName() : "none");
									ImGui::Text("Triangles: %4d", primitive.Count / 3);
								}
								ImGui::TreePop();
							}
							ImGui::TreePop();
						}
					}
					else
						ImGui::Text("No mesh");
					ImGui::TreePop();
				}
				ImGui::PopID();
			}
			ImGui::TreePop();
			ImGui::PopID();
		}
		if (ImGui::TreeNode("Material list"))
		{
			for (index_t i = 0; i < model->GetMaterialCount(); ++i)
			{
				cMaterial& material = *const_cast<cMaterial*>(&model->GetMaterial(i));
				if (ImGui::TreeNode(&material, "Material %d: %s", i, material.GetName()))
				{
					for (index_t j = 0; j < MATERIAL_TEXTURE_COUNT; ++j)
						ImGui::Text("%s: %s",
							GetMaterialTextureStr((eMaterialTexture)j), material.m_textures[j] ? material.m_textures[j]->m_description.debugName.c_str() : "none");
					ImGui::ColorEdit3("Albedo", &material.m_albedo[0]);
					ImGui::DragFloat("Metallic", &material.m_metallicFactor, 0.05f, 0.f, 1.f);
					ImGui::DragFloat("Roughness", &material.m_roughnessFactor, 0.05f, 0.f, 1.f);
					ImGui::ColorEdit3("Emissive", &material.m_emissiveFactor[0]);
					ImGui::DragFloat("Emissive strength", &material.m_emissiveStrength, 0.1f, 0.f, FLT_MAX);

					//ImGui::Button("Reload");
					ImGui::TreePop();
				}
			}
			ImGui::TreePop();
		}
	}

	index_t Scene::NewCamera()
	{
		index_t cameraIndex = m_cameras.GetSize();
		m_cameras.Push();
		return cameraIndex;
	}

	void Scene::SetCamera(sRenderObject r, const CameraComponent& cc)
	{
		check(IsValid(r));
		check(cc.CameraIndex < m_cameras.GetSize());
		m_cameraComponentMap[r] = cc;
		if (cc.Main)
			m_cameraIndex = cc.CameraIndex;
	}

	void Scene::PrepareMeshToDraw(rendersystem::RenderSystem* renderSystem, const cModel& model, uint32_t meshIndex, uint32_t transformOffset) const
	{
		const cMesh& mesh = model.GetMesh(meshIndex);
		renderSystem->SetVertexBuffer(mesh.GetVertexBuffer());
		renderSystem->SetIndexBuffer(mesh.GetIndexBuffer());
		renderSystem->SetShaderProperty("u_model", &m_renderTransforms[transformOffset + model.GetNodeFromMeshIndex(meshIndex)], sizeof(glm::mat4));
	}

	void Scene::LoadScene(const char* filepath)
	{
		PROFILE_SCOPE_LOGF(LoadScene, "Load scene (%s)", filepath);

		m_sceneFile = filepath;

		cFile file;
		check(file.OpenText(filepath, cFile::FileMode_Read) == cFile::Result_Ok);
		size_t size = file.GetContentSize();
		check(size);
		char* content = _new char[size];
		size_t contentReaded = file.Read(content, size, sizeof(char), size);
		file.Close();
		check(contentReaded <= size);
		content[contentReaded == size ? size - 1 : contentReaded] = 0;

		YAML::Node root = YAML::Load(content);
		check(root);
		YAML::Node envNode = root["Environment"];
		check(envNode);
		m_ambientColor = envNode["Ambient"].as<glm::vec3>();
		char skyboxTextures[Skybox::COUNT][256];
		strcpy_s(skyboxTextures[Skybox::FRONT], envNode["Skybox"]["Front"].as<std::string>().c_str());
		strcpy_s(skyboxTextures[Skybox::BACK], envNode["Skybox"]["Back"].as<std::string>().c_str());
		strcpy_s(skyboxTextures[Skybox::TOP], envNode["Skybox"]["Top"].as<std::string>().c_str());
		strcpy_s(skyboxTextures[Skybox::BOTTOM], envNode["Skybox"]["Bottom"].as<std::string>().c_str());
		strcpy_s(skyboxTextures[Skybox::LEFT], envNode["Skybox"]["Left"].as<std::string>().c_str());
		strcpy_s(skyboxTextures[Skybox::RIGHT], envNode["Skybox"]["Right"].as<std::string>().c_str());
		LoadSkybox(m_skybox,
			skyboxTextures[Skybox::FRONT],
			skyboxTextures[Skybox::BACK],
			skyboxTextures[Skybox::LEFT],
			skyboxTextures[Skybox::RIGHT],
			skyboxTextures[Skybox::TOP],
			skyboxTextures[Skybox::BOTTOM]);



		YAML::Node renderObjectSeq = root["RenderObjects"];
		check(renderObjectSeq);
		for (const auto& it : renderObjectSeq)
		{
			uint32_t parent = it["Parent"].as<uint32_t>();
			sRenderObject rb = CreateRenderObject(parent);
			SetRenderObjectName(rb, it["Name"].as<std::string>().c_str());

			TransformComponent t;
			YAML::Node transformNode = it["TransformComponent"];
			t.Position = transformNode["Position"].as<glm::vec3>();
			t.Rotation = transformNode["Rotation"].as<tAngles>();
			t.Scale = transformNode["Scale"].as<glm::vec3>();
			SetTransform(rb, t);

			YAML::Node lightNode = it["LightComponent"];
			if (lightNode)
			{
				LightComponent lightComponent;
				lightComponent.Enabled = lightNode["Enabled"].as<bool>();
				lightComponent.Color = lightNode["Color"].as<glm::vec3>();
				lightComponent.Strength = lightNode["Strength"].as<float>();
				lightComponent.Radius = lightNode["Radius"].as<float>();
				lightComponent.Compression = lightNode["Compression"].as<float>();
				lightComponent.OuterCutoff = lightNode["OuterCutoff"].as<float>();
				lightComponent.Cutoff = lightNode["Cutoff"].as<float>();
				lightComponent.ProjectShadows = lightNode["ProjectShadows"].as<bool>();
				lightComponent.Type = StrToLightType(lightNode["Type"].as<std::string>().c_str());
				lightComponent.OrthoLeft = lightNode["OrthoLeft"].as<float>();
				lightComponent.OrthoRight = lightNode["OrthoRight"].as<float>();
				lightComponent.OrthoBottom = lightNode["OrthoBottom"].as<float>();
				lightComponent.OrthoTop = lightNode["OrthoTop"].as<float>();
				lightComponent.NearClip = lightNode["NearClip"].as<float>();
				lightComponent.FarClip = lightNode["FarClip"].as<float>();
				SetLight(rb, lightComponent);
			}

			YAML::Node meshNode = it["MeshComponent"];
			if (meshNode)
			{
				MeshComponent m;
				strcpy_s(m.MeshAssetPath, meshNode["MeshAssetPath"].as<std::string>().c_str());
				m.MeshIndex = LoadModel(m.MeshAssetPath);
				SetMesh(rb, m);
			}

			YAML::Node cameraNode = it["CameraComponent"];
			if (cameraNode)
			{
				CameraComponent cc = { NewCamera() };
				cc.Main = cameraNode["Main"].as<bool>();
				SetCamera(rb, cc);
				Camera& camera = m_cameras[cc.CameraIndex].GetCamera();
				if (cameraNode["Position"] && cameraNode["Rotation"])
				{
					camera.SetPosition(cameraNode["Position"].as<glm::vec3>());
					camera.SetRotation(cameraNode["Rotation"].as<glm::vec3>());
				}
				else
					logferror("File with old version: %s\n", filepath);
			}
		}

		if (m_cameraIndex == index_invalid)
		{
			logwarn("Scene without main camara enabled. Creating one by default.\n");
			sRenderObject rb = CreateRenderObject(GetRoot());
			SetRenderObjectName(rb, "DefaultMainCamera");
			CameraComponent cc = { NewCamera() };
			cc.Main = true;
			SetCamera(rb, cc);
		}
		delete[] content;

		
		LoadIrradianceCube(*m_irradianceRequestInfo);
	}

	void Scene::SaveScene(const char* filepath)
	{
		YAML::Emitter emitter;

		emitter << YAML::BeginMap;
		emitter << YAML::Key << "Environment";
		{
			emitter << YAML::BeginMap;
			emitter << YAML::Key << "Ambient" << YAML::Value << m_ambientColor;
			emitter << YAML::Key << "Skybox" << YAML::BeginMap;
			emitter << YAML::Key << "Front" << YAML::Value << m_skybox.CubemapFiles[Skybox::FRONT];
			emitter << YAML::Key << "Back" << YAML::Value << m_skybox.CubemapFiles[Skybox::BACK];
			emitter << YAML::Key << "Top" << YAML::Value << m_skybox.CubemapFiles[Skybox::TOP];
			emitter << YAML::Key << "Bottom" << YAML::Value << m_skybox.CubemapFiles[Skybox::BOTTOM];
			emitter << YAML::Key << "Left" << YAML::Value << m_skybox.CubemapFiles[Skybox::LEFT];
			emitter << YAML::Key << "Right" << YAML::Value << m_skybox.CubemapFiles[Skybox::RIGHT];
			emitter << YAML::EndMap;
			emitter << YAML::EndMap;
		}
		emitter << YAML::Key << "RenderObjects";
		emitter << YAML::BeginSeq;
		for (uint32_t i = 0; i < GetRenderObjectCount(); ++i)
		{
			const Hierarchy& h = m_hierarchy[i];
			emitter << YAML::BeginMap;
			emitter << YAML::Key << "RenderObject" << YAML::Value << i;
			emitter << YAML::Key << "Name" << YAML::Value << GetRenderObjectName(i);
			emitter << YAML::Key << "Parent" << YAML::Value << h.Parent;

			const TransformComponent& t = m_transformComponents[i];
			emitter << YAML::Key << "TransformComponent" << YAML::BeginMap;
			emitter << YAML::Key << "Position" << YAML::Value << t.Position;
			emitter << YAML::Key << "Rotation" << YAML::Value << t.Rotation;
			emitter << YAML::Key << "Scale" << YAML::Value << t.Scale;
			emitter << YAML::EndMap;

			if (m_lightComponentMap.contains(i))
			{
				const LightComponent& light = m_lightComponentMap[i];
				emitter << YAML::Key << "LightComponent" << YAML::BeginMap;
				emitter << YAML::Key << "Type" << YAML::Value << LightTypeToStr(light.Type);
				emitter << YAML::Key << "Enabled" << YAML::Value << light.Enabled;
				emitter << YAML::Key << "Color" << YAML::Value << light.Color;
				emitter << YAML::Key << "Strength" << YAML::Value << light.Strength;
				emitter << YAML::Key << "Radius" << YAML::Value << light.Radius;
				emitter << YAML::Key << "Compression" << YAML::Value << light.Compression;
				emitter << YAML::Key << "OuterCutoff" << YAML::Value << light.OuterCutoff;
				emitter << YAML::Key << "Cutoff" << YAML::Value << light.Cutoff;
				emitter << YAML::Key << "ProjectShadows" << YAML::Value << light.ProjectShadows;
				emitter << YAML::Key << "OrthoLeft" << YAML::Value << light.OrthoLeft;
				emitter << YAML::Key << "OrthoRight" << YAML::Value << light.OrthoRight;
				emitter << YAML::Key << "OrthoBottom" << YAML::Value << light.OrthoBottom;
				emitter << YAML::Key << "OrthoTop" << YAML::Value << light.OrthoTop;
				emitter << YAML::Key << "NearClip" << YAML::Value << light.NearClip;
				emitter << YAML::Key << "FarClip" << YAML::Value << light.FarClip;
				emitter << YAML::EndMap;
			}

			if (m_meshComponentMap.contains(i))
			{
				emitter << YAML::Key << "MeshComponent" << YAML::BeginMap;
				const MeshComponent& mesh = m_meshComponentMap[i];
				emitter << YAML::Key << "MeshAssetPath" << YAML::Value << mesh.MeshAssetPath;
				emitter << YAML::EndMap;
			}

			if (m_cameraComponentMap.contains(i))
			{
				const CameraComponent& cc = m_cameraComponentMap.at(i);
				emitter << YAML::Key << "CameraComponent" << YAML::BeginMap;
				emitter << YAML::Key << "Main" << YAML::Value << cc.Main;
				check(cc.CameraIndex < m_cameras.GetSize());
				const Camera& camera = m_cameras[cc.CameraIndex].GetCamera();
				emitter << YAML::Key << "Position" << YAML::Value << camera.GetPosition();
				emitter << YAML::Key << "Rotation" << YAML::Value << camera.GetRotation();

				emitter << YAML::EndMap;
			}

			emitter << YAML::EndMap;
		}
		emitter << YAML::EndSeq;
		emitter << YAML::EndMap;

		check(emitter.good());
		const char* out = emitter.c_str();
		size_t size = emitter.size();
		//logfinfo("YAML %u b\n%s\n", size, out);
		cFile file;
		check(file.OpenText(filepath, cFile::FileMode_Write) == cFile::Result_Ok);
		file.Write(out, size);
		file.Close();

		logfok("--- Scene file saved in: %s (%d bytes) ---\n", filepath, size);
	}

	void Scene::DestroyRenderObject(sRenderObject object)
	{
		check(false && "not implemented yet" && __FUNCTION__ && __FILE__ && __LINE__);
	}

	const MeshComponent* Scene::GetMesh(sRenderObject renderObject) const
	{
		check(IsValid(renderObject));
		const MeshComponent* mesh = nullptr;
		if (m_meshComponentMap.contains(renderObject))
			mesh = &m_meshComponentMap.at(renderObject);
		return mesh;
	}

	void Scene::SetMesh(sRenderObject renderObject, const MeshComponent& meshComponent)
	{
		check(IsValid(renderObject));
		m_meshComponentMap[renderObject] = meshComponent;
	}

	const char* Scene::GetRenderObjectName(sRenderObject object) const
	{
		return IsValid(object) ? m_names[object.Id].c_str() : nullptr;
	}

	bool Scene::IsValid(sRenderObject object) const
	{
		return object.Id < GetRenderObjectCount();
	}

	uint32_t Scene::GetRenderObjectCount() const
	{
		return m_hierarchy.GetSize();
	}

	sRenderObject Scene::GetRoot() const
	{
		static sRenderObject root = 0;
		//for (; m_hierarchy[root].Parent.IsValid(); root = m_hierarchy[root].Parent);
		return root;
	}

	void Scene::SetRenderObjectName(sRenderObject renderObject, const char* name)
	{
		check(IsValid(renderObject));
		m_names[renderObject] = name;
	}

	const TransformComponent& Scene::GetTransform(sRenderObject renderObject) const
	{
		check(IsValid(renderObject));
		return m_transformComponents[renderObject];
	}

	void Scene::SetTransform(sRenderObject renderObject, const TransformComponent& transform)
	{
		check(IsValid(renderObject));
		m_transformComponents[renderObject] = transform;
		MarkAsDirty(renderObject);
	}

	const LightComponent* Scene::GetLight(sRenderObject renderObject) const
	{
		check(IsValid(renderObject));
		const LightComponent* light = nullptr;
		if (m_lightComponentMap.contains(renderObject))
			light = &m_lightComponentMap.at(renderObject);
		return light;
	}

	void Scene::SetLight(sRenderObject renderObject, const LightComponent& light)
	{
		check(IsValid(renderObject));
		m_lightComponentMap[renderObject] = light;
	}

	void Scene::MarkAsDirty(sRenderObject renderObject)
	{
		check(IsValid(renderObject));
		int32_t level = m_hierarchy[renderObject].Level;
		m_dirtyNodes[level].Push(renderObject);
		for (sRenderObject child = m_hierarchy[renderObject].Child; child.IsValid(); child = m_hierarchy[child].Sibling)
			MarkAsDirty(child);
	}


	void Scene::RecalculateTransforms()
	{
		CPU_PROFILE_SCOPE(RecalculateTransforms);
		{
			CPU_PROFILE_SCOPE(TransformComponentToMatrices);
			check(m_localTransforms.GetSize() == m_transformComponents.GetSize());
			check(m_globalTransforms.GetSize() == m_transformComponents.GetSize());
			TransformComponentToMatrix(m_transformComponents.GetData(), m_localTransforms.GetData(), m_transformComponents.GetSize());
		}
		{
			CPU_PROFILE_SCOPE(SceneUpdate);
			// Process root level first
			if (!m_dirtyNodes[0].IsEmpty())
			{
				for (uint32_t i = 0; i < m_dirtyNodes[0].GetSize(); ++i)
				{
					uint32_t nodeIndex = m_dirtyNodes[0][i];
					m_globalTransforms[nodeIndex] = m_localTransforms[nodeIndex];
				}
				m_dirtyNodes[0].Clear();
			}
			// Iterate over the deeper levels
			for (uint32_t level = 1; level < MaxNodeLevel; ++level)
			{
				for (uint32_t nodeIndex = 0; nodeIndex < m_dirtyNodes[level].GetSize(); ++nodeIndex)
				{
					int32_t node = m_dirtyNodes[level][nodeIndex];
					int32_t parentNode = m_hierarchy[node].Parent;
					m_globalTransforms[node] = m_globalTransforms[parentNode] * m_localTransforms[node];
				}
				m_dirtyNodes[level].Clear();
			}
		}

		{
			CPU_PROFILE_SCOPE(ModelUpdate);
			index_t offset = 0;
			for (index_t i = 0; i < m_hierarchy.GetSize(); ++i)
			{
				if (m_meshComponentMap.contains(i))
				{
					index_t meshIndex = m_meshComponentMap[i].MeshIndex;
					const cModel& model = m_models[meshIndex];
					uint32_t count = model.GetTransformsCount();
					check(offset + count < m_renderTransforms.GetSize());
					model.UpdateRenderTransforms(m_renderTransforms.GetData() + offset, m_globalTransforms[i]);
					offset += count;
				}
			}
		}

	}

	bool Scene::LoadSkybox(Skybox& skybox, const char* front, const char* back, const char* left, const char* right, const char* top, const char* bottom)
	{
		PROFILE_SCOPE_LOG(LoadSkybox, "LoadSkybox");

		strcpy_s(skybox.CubemapFiles[Skybox::FRONT], front);
		strcpy_s(skybox.CubemapFiles[Skybox::BACK], back);
		strcpy_s(skybox.CubemapFiles[Skybox::LEFT], left);
		strcpy_s(skybox.CubemapFiles[Skybox::RIGHT], right);
		strcpy_s(skybox.CubemapFiles[Skybox::TOP], top);
		strcpy_s(skybox.CubemapFiles[Skybox::BOTTOM], bottom);

		// Load textures from files
		rendersystem::textureloader::TextureData textureData[Skybox::COUNT];
		const uint8_t* pixelsArray[Skybox::COUNT];
		for (uint32_t i = 0; i < Skybox::COUNT; ++i)
		{
			check(rendersystem::textureloader::LoadTextureData_u8(&textureData[i], skybox.CubemapFiles[i]));
			pixelsArray[i] = textureData[i].u8data;
			if (i)
				check(textureData[i - 1].width == textureData[i].width &&
					textureData[i - 1].height == textureData[i].height &&
					textureData[i - 1].channels == textureData[i].channels);
		}
		uint64_t textureSize = textureData[0].width * textureData[0].height * sizeof(uint8_t) * textureData[0].channels;

		render::TextureDescription texDesc;
		texDesc.extent = { textureData[0].width, textureData[0].height, 1 };
		texDesc.format = render::Format_R8G8B8A8_UNorm;
		texDesc.layers = Skybox::COUNT;
		texDesc.dimension = render::ImageDimension_Cube;
		texDesc.debugName = "cubemap";
		skybox.texture = g_device->CreateTexture(texDesc);

		render::utils::UploadContext upload(g_device);
		for (uint32_t i = 0; i < Skybox::COUNT; ++i)
		{
			upload.WriteTexture(skybox.texture, 0, i, pixelsArray[i], textureSize);
			upload.SetTextureLayout(skybox.texture, render::ImageLayout_ShaderReadOnly, i);
		}
		upload.Submit();

		return true;
	}

	bool Scene::LoadIrradianceCube(const PreprocessIrradianceInfo& info)
	{
		const Renderer* renderer = m_engine->GetRenderer();
		Preprocess* preprocess = (Preprocess*)renderer->GetRenderProcess(RENDERPROCESS_PREPROCESSES);
		m_irradianceCube.filepath = info.hdrFilepath;
		check(info.userData == this);
		preprocess->PushIrradiancePreprocess(info, 
			[](const PreprocessIrradianceResult& result, void* userData) 
			{
				Scene* scene = (Scene*)userData;
				// copy result
				scene->m_irradianceCube.irradiance = result.irradianceCubemap;
				scene->m_irradianceCube.cubemap = result.cubemap;
				scene->m_irradianceCube.specular = result.specularCubemap;
				scene->m_irradianceCube.brdf = result.brdf;
			});
		return true;
	}

	cModel* Scene::GetModel(const char* modelName)
	{
		for (uint32_t i = 0; i < m_models.GetSize(); ++i)
		{
			if (!strcmp(m_models[i].GetName(), modelName))
				return &m_models[i];
		}
		return nullptr;
	}

	render::TextureHandle Scene::GetSkyboxTexture() const
	{
		if (!m_irradianceCube.brdf) 
			return m_skybox.texture;

		if (CVar_DebugCubes.Get() == 1)
			return m_irradianceCube.irradiance;
		if (CVar_DebugCubes.Get() == 2)
			return m_irradianceCube.specular;
		return m_irradianceCube.cubemap;
	}

	void Scene::ImGuiDraw()
	{
		ImGui::Begin("SceneGraph");

		float posStep = 0.5f;
		float rotStep = 0.1f;
		float sclStep = 0.5f;

		char tempSceneFile[256];
		strcpy_s(tempSceneFile, m_sceneFile.GetAssetPath());

		ImGui::Columns(3);
		if (ImGui::Button("Save"))
			SaveScene(tempSceneFile);
		ImGui::NextColumn();
		if (ImGui::Button("Load"))
			LoadScene(tempSceneFile);
		ImGui::NextColumn();
		if (ImGui::InputText("Scene file", tempSceneFile, 256))
			m_sceneFile = tempSceneFile;
		ImGui::Columns();

		ImGui::Separator();
		ImGui::Text("Environment");
		ImGui::ColorEdit3("Ambient color", &m_ambientColor[0]);
		ImGui::Button("Reload");

		ImGui::Separator();
		if (ImGui::TreeNode("Scene tree"))
		{
			for (uint32_t i = 0; i < GetRenderObjectCount(); ++i)
			{
				ImGui::PushID(i);
				if (ImGui::TreeNode("ObjectTree", GetRenderObjectName(i)))
				{
					glm::mat4 transform;
					TransformComponentToMatrix(&m_transformComponents[i], &transform, 1);
					DebugRender::DrawAxis(transform);
					const Hierarchy& node = m_hierarchy[i];
					ImGui::Text("Parent: %s", node.Parent != UINT32_MAX ? GetRenderObjectName(node.Parent) : "None");
					if (ImGui::TreeNode("Transform component"))
					{
						TransformComponent t = m_transformComponents[i];
						ImGui::Columns(2);
						ImGui::Text("Position");
						ImGui::NextColumn();
						bool dirty = ImGui::DragFloat3("Position", &t.Position[0], posStep);
						ImGui::NextColumn();
						dirty |= ImGuiUtils::EditAngles("Rotation", "Rotation", t.Rotation);
						ImGui::NextColumn();
						ImGui::Text("Scale");
						ImGui::NextColumn();
						dirty |= ImGui::DragFloat3("Scale", &t.Scale[0], sclStep);
						ImGui::Columns();
						ImGui::TreePop();

						if (dirty)
							SetTransform(i, t);
					}
					if (m_lightComponentMap.contains(i))
					{
						if (ImGui::TreeNode("Light component"))
						{
							LightComponent& light = m_lightComponentMap[i];
							ImGui::PushID(i);
							ImGui::Checkbox("Enabled", &light.Enabled);
							static const char* lightTypes[] = { "Point", "Directional", "Spot" };
							uint32_t lightCount = sizeof(lightTypes) / sizeof(const char*);
							if (ImGui::BeginCombo("Type", lightTypes[(uint32_t)light.Type]))
							{
								for (uint32_t j = 0; j < lightCount; ++j)
								{
									if (ImGui::Selectable(lightTypes[j], j == (uint32_t)light.Type))
										light.Type = (ELightType)j;
								}
								ImGui::EndCombo();
							}
							ImGui::Columns(2);
							ImGui::Text("Color");
							ImGui::NextColumn();
							ImGui::ColorEdit3("Color", &light.Color[0]);
							ImGui::NextColumn();
							ImGui::Text("Strength");
							ImGui::NextColumn();
							ImGui::DragFloat("Strength", &light.Strength, 0.2f, 0.f, FLT_MAX);
							ImGui::NextColumn();
							ImGui::Text("Radius");
							ImGui::NextColumn();
							ImGui::DragFloat("Radius", &light.Radius, 0.5f, 0.f, FLT_MAX);
							ImGui::NextColumn();
							ImGui::Text("Compression");
							ImGui::NextColumn();
							ImGui::DragFloat("Compression", &light.Compression, 0.05f, 0.f, FLT_MAX);
							ImGui::NextColumn();
							ImGui::Text("Outer cutoff");
							ImGui::NextColumn();
							ImGui::DragFloat("OuterCutoff", &light.OuterCutoff, 0.1f, 0.f, FLT_MAX);
							ImGui::NextColumn();
							ImGui::Text("Cutoff");
							ImGui::NextColumn();
							ImGui::DragFloat("Cutoff", &light.Cutoff, 0.1f, 0.f, FLT_MAX);
							ImGui::NextColumn();
							ImGui::Text("Project shadows");
							ImGui::NextColumn();
							ImGui::Checkbox("Shadows enabled", &light.ProjectShadows);
							ImGui::NextColumn();

							ImGui::Text("Near clip");
							ImGui::NextColumn();
							ImGui::DragFloat("Near clip", &light.NearClip, 1.f);
							ImGui::NextColumn();

							ImGui::Text("Far clip");
							ImGui::NextColumn();
							ImGui::DragFloat("Far clip", &light.FarClip, 1.f);
							ImGui::NextColumn();

							ImGui::Text("Ortho left");
							ImGui::NextColumn();
							ImGui::DragFloat("Left", &light.OrthoLeft, 1.f);
							ImGui::NextColumn();

							ImGui::Text("Ortho right");
							ImGui::NextColumn();
							ImGui::DragFloat("Right", &light.OrthoRight, 1.f);
							ImGui::NextColumn();

							ImGui::Text("Ortho bottom");
							ImGui::NextColumn();
							ImGui::DragFloat("Bottom", &light.OrthoBottom, 1.f);
							ImGui::NextColumn();

							ImGui::Text("Ortho top");
							ImGui::NextColumn();
							ImGui::DragFloat("Top", &light.OrthoTop, 1.f);
							ImGui::NextColumn();

							ImGui::Columns();

							// Draw debug
							switch (light.Type)
							{
							case ELightType::Point:
								DebugRender::DrawSphere(m_transformComponents[i].Position, light.Radius, light.Color, 32);
								break;
							case ELightType::Directional:
							{
								glm::mat4 vp = GetLightVPMatrix(m_transformComponents[i].Position, m_transformComponents[i].Rotation, 
									light.OrthoLeft, light.OrthoRight, light.OrthoBottom, light.OrthoTop, light.NearClip, light.FarClip);
								Frustum f(vp);
								f.DrawDebug(light.Color);
							}
								break;
							case ELightType::Spot:
							{
								glm::mat4 vp = GetLightVPMatrix(m_transformComponents[i].Position, m_transformComponents[i].Rotation, 
									light.Cutoff, light.NearClip, light.FarClip);
								Frustum f(vp);
								f.DrawDebug(light.Color);
							}
								break;
							default:
								break;

							}
							ImGui::PopID();

							ImGui::TreePop();
						}
					}
					if (m_meshComponentMap.contains(i))
					{
						if (ImGui::TreeNode("Mesh component"))
						{
							const MeshComponent& meshComp = m_meshComponentMap.at(i);
							const cModel& model = m_models[meshComp.MeshIndex];
							AABB_t aabb = model.GetAABB().ApplyTransform(transform);
							DebugRender::DrawBox(aabb.min, aabb.max, glm::vec3(0, 1, 0));
							ImGui::Text("Model: [%u] %s", meshComp.MeshIndex, meshComp.MeshAssetPath);
							ImGui::Text("Model name: %s", model.GetName());
							if (ImGui::Button("Dump info"))
								model.DumpInfo();
							if (ImGui::TreeNode("Meshes"))
							{
								for (uint32_t j = 0; j < model.GetMeshCount(); ++j)
								{
									const cMesh& mesh = model.GetMesh(j);
									aabb = mesh.GetAABB().ApplyTransform(transform);
									ImGui::Text("%s [%4d triangles; %4d indices; %3d primitives] (VB: %lld B; IB: %lld B) (Extent: (%3.3f, %3.3f, %3.3f; %3.3f, %3.3f, %3.3f))",
										mesh.GetName(), mesh.GetIndexCount()/3, mesh.GetIndexCount(), mesh.GetPrimitiveCount(),
										mesh.GetVertexBuffer()->m_description.size, mesh.GetIndexBuffer()->m_description.size,
										aabb.min.x, aabb.min.y, aabb.min.z,
										aabb.max.x, aabb.max.y, aabb.max.z);
									if (*CVar_ShowAABBMeshName.Get() && WildStricmp(CVar_ShowAABBMeshName.Get(), mesh.GetName()))
										DebugRender::DrawBox(aabb.min, aabb.max, glm::vec3(1, 1, 0));
								}
								ImGui::TreePop();
							}
							ImGui::TreePop();
						}
					}

					if (m_cameraComponentMap.contains(i))
					{
						if (ImGui::TreeNode("Camera Component"))
						{
							CameraComponent& cc = m_cameraComponentMap[i];
							Frustum f(m_cameras[cc.CameraIndex].GetCamera().GetProjection() * m_cameras[cc.CameraIndex].GetCamera().GetView());
							f.DrawDebug(glm::vec3(1,0,1));
							m_cameras[cc.CameraIndex].GetCamera().ImGuiDraw();
							ImGui::TreePop();
						}
					}
					ImGui::TreePop();
				}
				ImGui::PopID();
			}
			ImGui::TreePop();
		}
		if (ImGui::TreeNode("Model list"))
		{
			ImGui::Columns(2);
			char buff[32];
			for (index_t i = 0; i < m_models.GetSize(); ++i)
			{
				ImGui::Text("Model: %s", m_models[i].GetName());
				ImGui::NextColumn();
				sprintf_s(buff, "##modelbutton_%d", i);
				ImGui::PushID(buff);
				if (ImGui::Button("..."))
				{ 
					logfinfo("editing model %s\n", m_models[i].GetName());
					m_editingModel = i;
				}
				ImGui::PopID();
				ImGui::NextColumn();
			}
			ImGui::Columns();
			ImGui::TreePop();

			if (m_editingModel != index_invalid)
			{
				ImGui::PushStyleColor(ImGuiCol_ChildBg, ImGui::GetStyleColorVec4(ImGuiCol_FrameBg));
				if (ImGui::BeginChild("EditingModelChild", ImVec2(-FLT_MIN, ImGui::GetTextLineHeightWithSpacing() * 8), ImGuiChildFlags_Borders | ImGuiChildFlags_ResizeY))
				{
					ImGui::Text("Editing model %s", m_models[m_editingModel].GetName());
					ImGui::Separator();
					//m_models[m_editingModel].ImGuiDraw();
					//ImGuiDrawModel(m_models[m_editingModel], )
				}
				ImGui::PopStyleColor();
				ImGui::EndChild();
			}
		}
		if (ImGui::TreeNode("IBL cubemap"))
		{
			if (ImGui::Button("Reload IBL"))
				LoadIrradianceCube(*m_irradianceRequestInfo);
			char buff[256];
			strcpy_s(buff, m_irradianceRequestInfo->hdrFilepath);
			if (ImGui::InputText("HDR filepath", buff, sizeof(buff)))
				m_irradianceRequestInfo->hdrFilepath = buff;
			int res = m_irradianceRequestInfo->cubemapWidthHeight;
			if (ImGui::DragInt("Cubemap resolution", &res, 1.f, 0, 8192, "%5d"))
				m_irradianceRequestInfo->cubemapWidthHeight = res;
			res = m_irradianceRequestInfo->irradianceCubemapWidthHeight;
			if (ImGui::DragInt("Convolution irradiance resolution", &res, 1.f, 0, 512, "%5d"))
				m_irradianceRequestInfo->irradianceCubemapWidthHeight = res;
			res = m_irradianceRequestInfo->specularCubemapWidthHeight;
			if (ImGui::DragInt("Specular irradiance resolution", &res, 1.f, 0, 1024, "%5d"))
				m_irradianceRequestInfo->specularCubemapWidthHeight = res;
			ImGui::DragFloat3("Min cubemap color", &m_irradianceRequestInfo->minCubemapClamp[0], 0.5f, 0.f, FLT_MAX);
			ImGui::DragFloat3("Max cubemap color", &m_irradianceRequestInfo->maxCubemapClamp[0], 0.5f, 0.f, FLT_MAX);
			ImGui::TreePop();
		}
		ImGui::End();

		CameraController& camera = GetCamera();
		camera.ImGuiDraw();
	}

	bool Scene::IsDirty() const
	{
		for (uint32_t i = 0; i < MaxNodeLevel; ++i)
		{
			if (!m_dirtyNodes[i].IsEmpty())
				return true;
		}
		return false;
	}

	void Scene::UpdateRenderData()
	{
		CPU_PROFILE_SCOPE(SceneUpdateRenderData);
		if (GetRenderObjectCount())
		{
			// Update geometry
			RecalculateTransforms();
			check(!IsDirty());
			const glm::mat4& viewMat = GetCameraData()->View;
			ProcessEnvironmentData(viewMat, m_environmentData);
		}
	}

	const glm::mat4* Scene::GetRawGlobalTransforms() const
	{
		check(!IsDirty());
		return m_globalTransforms.GetData();
	}

	void Scene::ProcessEnvironmentData(const glm::mat4& viewSpace, EnvironmentData& environmentData)
	{
		CPU_PROFILE_SCOPE(ProcessEnvData);
		environmentData.Reset();
		environmentData.ambientColor = m_ambientColor;
		VulkanRenderEngine* engine = IRenderEngine::GetRenderEngineAs<VulkanRenderEngine>();
		ShadowMapProcess* shadowMapping = engine->GetRenderer()->GetRenderProcessAs<ShadowMapProcess>();

		for (uint32_t i = 0; i < GetRenderObjectCount(); ++i)
		{
			if (m_lightComponentMap.contains(i))
			{
				const LightComponent& light = m_lightComponentMap[i];
				if (!light.Enabled)
					continue;
				const TransformComponent& transform = m_transformComponents[i];
				const glm::mat4& mat = m_globalTransforms[i];
				const glm::vec3 pos = math::GetPos(viewSpace * mat);
				const glm::vec3 dir = -1.f*math::GetDir(viewSpace * mat);

				uint32_t shadowMapIndex = UINT32_MAX;
				if (light.ProjectShadows && light.Type != ELightType::Point)
					shadowMapIndex = light.Type == ELightType::Directional
					? shadowMapping->SetupDirectionalLight(transform.Position, transform.Rotation, light.OrthoLeft, light.OrthoRight, light.OrthoTop, light.OrthoBottom, light.NearClip, light.FarClip)
					: shadowMapping->SetupSpotLight(transform.Position, transform.Rotation, light.OuterCutoff, light.NearClip, light.FarClip);

				environmentData.PushLight(light, pos, dir, shadowMapIndex != UINT32_MAX ? static_cast<int>(shadowMapIndex) : -1);
			}
		}
	}

	SceneRenderer::SceneRenderer(uint32_t size)
	{
		m_creationInfo.Allocate(size);
		m_renderPasses.Allocate(size);
	}

	SceneRenderer::~SceneRenderer()
	{
		m_renderPasses.Delete();
		m_creationInfo.Delete();
	}

	uint32_t SceneRenderer::CreateRenderList(const RenderPassInfo& info)
	{
		check(((info.pass & (RenderPass_Opaque|RenderPass_Transparent)) && !(info.pass & RenderPass_ShadowMap)) || (info.pass & RenderPass_ShadowMap) == info.pass);
		m_creationInfo.Push(info);
		m_renderPasses.Push();
		return m_renderPasses.GetSize()-1;
	}

	void SceneRenderer::SetRenderListInfo(uint32_t id, const RenderPassInfo& info)
	{
		check(id < m_creationInfo.GetSize());
		m_creationInfo[id] = info;
	}

	void SceneRenderer::BuildRenderLists(const Scene* scene)
	{
		CPU_PROFILE_SCOPE(BuildRenderLists);
		if (!scene)
			return;
		check(m_renderPasses.GetSize() == m_creationInfo.GetSize());
		for (uint32_t i = 0; i < m_renderPasses.GetSize(); ++i)
			m_renderPasses[i].Clear();

		const glm::mat4* worldTransforms = scene->GetRawGlobalTransforms();
		for (uint32_t i = 0; i < scene->GetRenderObjectCount(); ++i)
		{
			const MeshComponent* mc = scene->GetMesh(i);
			if (mc)
			{
				check(mc->MeshIndex != UINT32_MAX);
				const cModel* model = scene->GetModel(mc->MeshIndex);
				ProcessModelNode(model, model->GetRoot(), worldTransforms[i], worldTransforms[i]);
			}
		}
		DoCulling();
	}

	void SceneRenderer::DrawList(const RenderContext& renderContext)
	{
		check(renderContext.rs);
		check(renderContext.passId < m_renderPasses.GetSize());
		check(renderContext.passId < m_creationInfo.GetSize());

		RenderPass& pass = m_renderPasses[renderContext.passId];
		const cMaterial* lastMaterial = nullptr;
		const cMesh* lastMesh = nullptr;
		if (!IsGeometryPass(m_creationInfo[renderContext.passId].pass))
		{
			CPU_PROFILE_SCOPE(Scene_Draw);
			if (IsCullingEnabled())
			{ 
				for (uint32_t i = 0; i < pass.drawList.size(); ++i)
					DrawItem(renderContext, pass.items[pass.drawList[i]], lastMesh, lastMaterial);
			}
			else
			{
				for (uint32_t i = 0; i < pass.items.size(); ++i)
					DrawItem(renderContext, pass.items[i], lastMesh, lastMaterial);
			}
		}
		else
		{
			CPU_PROFILE_SCOPE(Scene_DrawGeometry);
			for (uint32_t i = 0; i < pass.items.size(); ++i)
				DrawGeometryItem(renderContext, pass.items[i]);
		}
	}

	void SceneRenderer::ImGuiDraw()
	{
		ImGui::Begin("SceneRenderer");
		{
			char buff[256];
			for (uint32_t i = 0; i < m_renderPasses.GetSize(); ++i)
			{
				sprintf_s(buff, "RenderPass_%d", i);
				ImGui::PushID(buff);
				if (ImGui::TreeNode(buff))
				{
					ImGui::Text("Mask			: %d", m_creationInfo[i].pass);
					ImGui::Text("Item count		: %d", m_renderPasses[i].items.size());
					ImGui::Text("Culling count	: %d", m_renderPasses[i].drawList.size());
					if (ImGui::TreeNode("Draw list"))
					{
						for (uint32_t j = 0; j < m_renderPasses[i].items.size(); ++j)
						{
							ImGui::Text("(#%3d) mesh: %s; primitive: %d; material: 0x%p",
								j,
								m_renderPasses[i].items[j].mesh->GetName(),
								m_renderPasses[i].items[j].primitive,
								m_renderPasses[i].items[j].mesh->GetPrimitiveArray()[m_renderPasses[i].items[j].primitive].Material);
						}
						ImGui::TreePop();
					}

					ImGui::TreePop();
				}
				ImGui::PopID();
			}
		}
		ImGui::End();
	}

	void SceneRenderer::Init()
	{
		check(!g_sceneRenderer);
		g_sceneRenderer = _new SceneRenderer(8);
	}

	void SceneRenderer::Destroy()
	{
		check(g_sceneRenderer);
		delete g_sceneRenderer;
	}

	SceneRenderer* SceneRenderer::GetSceneRenderer()
	{
		check(g_sceneRenderer);
		return g_sceneRenderer;
	}

	void SceneRenderer::ProcessModelNode(const cModel* model, index_t nodeIndex, const glm::mat4& parentTransform, const glm::mat4& worldTransform)
	{
		check(model && nodeIndex != index_invalid);
		glm::mat4 transform = parentTransform * model->GetTransform(nodeIndex);
		const cModel::sNode& node = *model->GetNode(nodeIndex);
		if (node.MeshId != index_invalid)
			ProcessMesh(model->GetMesh(node.MeshId), transform, worldTransform);
		if (node.Sibling != index_invalid)
			ProcessModelNode(model, node.Sibling, parentTransform, worldTransform);
		if (node.Child != index_invalid)
			ProcessModelNode(model, node.Child, transform, worldTransform);
	}

	void SceneRenderer::ProcessMesh(const cMesh& mesh, const glm::mat4& nodeTransform, const glm::mat4& modelTransform)
	{
		// process mesh flags
		static constexpr uint32_t maxCount = 8;
		check(m_creationInfo.GetSize() <= maxCount);
		struct  
		{
			uint32_t indices[maxCount];
			uint32_t index = 0;
		} primitiveRenderPasses;

		if (!SceneFilter(mesh.GetName()))
			return;

		for (uint32_t i = 0; i < m_creationInfo.GetSize(); ++i)
		{
			AABB_t aabb = mesh.GetAABB().ApplyTransform(modelTransform);
			if ((mesh.GetRenderFlags() & m_creationInfo[i].pass) && (IsAABBVisibleConditional(aabb, Frustum(m_creationInfo[i].cameraData.ViewProjection))))
			{
				if (!IsGeometryPass(m_creationInfo[i].pass))
					primitiveRenderPasses.indices[primitiveRenderPasses.index++] = i;
				else if (m_creationInfo[i].pass & RenderPass_ShadowMap)
				{
					// add whole mesh to the list
					RenderItem& item = m_renderPasses[i].items.emplace_back();
					item.mesh = &mesh;
					item.primitive = UINT32_MAX;
					item.transform = nodeTransform;
				}
			}
		}

		// primitive lists
		for (uint32_t i = 0; i < mesh.GetPrimitiveCount(); ++i)
		{
			const PrimitiveMeshData& primitive = mesh.GetPrimitiveArray()[i];
			for (uint32_t j = 0; j < primitiveRenderPasses.index; ++j)
			{
				check(primitive.Material);
				const RenderPassInfo& info = m_creationInfo[primitiveRenderPasses.indices[j]];
				RenderPass& pass = m_renderPasses[primitiveRenderPasses.indices[j]];
				if (primitive.RenderFlags & info.pass)
				{
					// Render info
					RenderItem& item = pass.items.emplace_back();
					item.mesh = &mesh;
					item.primitive = i;
					item.transform = nodeTransform;

					// Culling info
					pass.cullingData.emplace_back(primitive.AABB.ApplyTransform(modelTransform));
				}
			}
		}
	}

	void SceneRenderer::BindMesh(rendersystem::RenderSystem* rs, const RenderItem& item)
	{
		rs->SetVertexBuffer(item.mesh->GetVertexBuffer());
		rs->SetIndexBuffer(item.mesh->GetIndexBuffer());
		rs->SetShaderProperty("u_model", &item.transform, sizeof(item.transform));
		rs->SetShaderProperty("u_prevModel", &item.transform, sizeof(item.transform));
	}

	void SceneRenderer::BindMaterial(rendersystem::RenderSystem* rs, const cMaterial& material)
	{
		material.BindTextures(rs);
		sMaterialRenderData materialData = material.GetRenderData();
		rs->SetShaderProperty("u_material", &materialData, sizeof(materialData));
	}

	void SceneRenderer::DoCulling()
	{
		CPU_PROFILE_SCOPE(Culling);
		if (!IsCullingEnabled())
			return;
		for (uint32_t i = 0; i < m_creationInfo.GetSize(); ++i)
		{
			// Culling already done before insert mesh on the list
			if (IsGeometryPass(m_creationInfo[i].pass))
				continue;
			const CameraData& cd = m_creationInfo[i].cameraData;
			Frustum f(cd.ViewProjection);
			RenderPass& pass = m_renderPasses[i];
			check(pass.cullingData.size() == pass.items.size());

			for (uint32_t j = 0; j < pass.cullingData.size(); ++j)
			{
				const AABB_t& aabb = pass.cullingData[j];
				if (IsAABBVisible(aabb, f))
					pass.drawList.emplace_back(j);
			}
		}
	}

	void SceneRenderer::DrawItem(const RenderContext& renderContext, const RenderItem& item, const cMesh*& lastMesh, const cMaterial*& lastMaterial)
	{
		const PrimitiveMeshData& primitive = item.mesh->GetPrimitiveArray()[item.primitive];

		if (lastMesh != item.mesh)
		{
			lastMesh = item.mesh;
			BindMesh(renderContext.rs, item);
		}
		if (lastMaterial != primitive.Material)
		{
			lastMaterial = primitive.Material;
			BindMaterial(renderContext.rs, *primitive.Material);
		}
		renderContext.rs->DrawIndexed(primitive.Count, 1, primitive.FirstIndex);
	}

	void SceneRenderer::DrawGeometryItem(const RenderContext& renderContext, const RenderItem& item)
	{
		BindMesh(renderContext.rs, item);
		renderContext.rs->DrawIndexed(item.mesh->GetIndexCount());
	}

}

